### ISSUE TITLE
Quest In Defense of Far Watch tracking wrong

### ISSUE THREAD

**Issue by reknov** [SallyWhitemane/Herod#100]
**Description:**
Minor issue, quest In Defense of Fat Watch in Northern Barrens does not track your Razormane Hunter kills and disappears of map tracking after you've killed the other credits for the quest

**How to reproduce:**
Kill the mobs in the quest and recieve credit but not tracking

**How it should work:**
Should track how many quest mobs you've killed
![WoWScrnShot_041321_011718](https://user-images.githubusercontent.com/82418787/114469575-174b4100-9bf6-11eb-93f5-b7c15e910a8c.jpg)
![WoWScrnShot_041321_011710](https://user-images.githubusercontent.com/82418787/114469583-19ad9b00-9bf6-11eb-9f82-03e1102c511e.jpg)

**Comment by HerodDev** [comment]
fixed in rev 15
