### ISSUE TITLE
Quest "Vortex" in ashenvale

### ISSUE THREAD

**Issue by herodbetatester** [SallyWhitemane/Herod#108]
**Description:**
the ability to return to the quest giver is bugged, it will not return u to the quest giver, i tryed pressing multiply time and it ended up dissmounting me in mid air and it kill me.

**How to reproduce:**

**How it should work:**

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=13888/vortex

**Comment by HerodDev** [comment]
fixed in rev 15
