### ISSUE TITLE
Scarlet Executioner : WPL

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#110]
**Description:**
Level 37 Rare, 51.00, 40.50, autos for over 400 damage and does 400 cleaves, 850 mortal strikes, for reference my 39 shaman has 1,600 HP.

**How to reproduce:**
attack him at a level appropriate of the area.

**How it should work:**
less damage :P

**Comment by HerodDev** [comment]
fixed in rev 15
