### ISSUE TITLE
Fallen Heroes now bugged in Icecrown

### ISSUE THREAD

**Issue by Confessed88** [SallyWhitemane/Herod#113]
**Description:**
Fallen Heroes no longer aggro with AOE, they stand still, put you in combat and patrol as if they have not been attacked.

**How to reproduce:**
AOE groups and they will put you in combat but not react to damage and regen.

**How it should work:**
Like it did before, AoE damage should aggro anyone hit by it.

**Comment by GitGudNubHub** [comment]
What do you mean fallen heroes in Icecrown? Max lvl is 60

**Comment by Confessed88** [comment]
This is is now fixed/resolved. I meant "Converted Heroes" in Icecrown. Thank you!
