### ISSUE TITLE
Missing quest The Last Stand

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Herod#115]
**Description:**
After returning completed [Clear the Shrine] quest to Big Baobob, NPC doesn't offer follow-up quest [The Last Stand]. At this moment it's not even beginnable and relog didn't change anything

**How to reproduce:**
Turn in Clear the Shrine quest to NPC -> take follow-up(try)

**How it should work:**
After turning in [Clear the Shrine] quest, Big Baobob should offer you quest [The Last Stand]

**Comment by HerodDev** [comment]
fixed rev 17
