### ISSUE TITLE
Gurubashi Challenge quests bugged

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#117]
**Description:**
The 2 quests you can take from Stone Guard Towhide, dont work properly.
When you take up the quest and go into the arena to summon your enemy with the Gurubashi Challenge flag.
However instead of an opponent appearing with the same lvl as you, a skull leveled weapon appears that oneshots you as soon as you summon it. But there is even more to that because when you die to it, the summoned enemy wont disappear and you can basically stack them infinitely in the arena. Which makes it impossible to complete the quest even if it is fixed, because as soon as you go into the arena you get oneshot by every opponent that was left there during other people's failure to kill them.

**How to reproduce:**
Take the quest Gurubashi Challenge or Gurubashi Challenge: Free-For-All Arena Combat.
Go into the arena, summon your opponent by using the Gurubashi Challenge flag quest item.
Get onesot by a skull leveled floating weapon
![WoWScrnShot_041321_105525](https://user-images.githubusercontent.com/58514021/114526960-bfd5c100-9c47-11eb-8d14-e560fda4de87.jpg)

**How it should work:**
The flag should summon a mob equal level to you.
And if you fail to kill it, it should despawn in 3 minutes.

**Comment by SallyWhitemane** [comment]
Fixed in rev 28.
