### ISSUE TITLE
High Priestess Jeklik quest bugged

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#118]
**Description**:
After doing this quest https://www.wowhead.com/quest=26553/high-priestess-jeklik#videos.
You should get the follow up quest instantly : https://www.wowhead.com/quest=26554/plunging-into-zulgurub#videos:id=51492
where you could go into the portal in front of you, by clicking it. But you dont get the quest, and you cant even go into the portal.
**How to reproduce**:
Finish the High Priestess Jeklik quest, complete it, try going into the portal
**How it should work**:
You should get the next quest after completing the current one, and you should be able to go to the portal by clicking it.
![WoWScrnShot_041321_112946](https://user-images.githubusercontent.com/58514021/114531565-4d1b1480-9c4c-11eb-94f8-ea00c169e2b5.jpg)

**Comment by Bluecow941** [comment]
Can confirm that there is no follow up quest right after you complete quest. Somehow after you use fetish item to return to npc and teleport back to Zul'Gurrub after you talk to her, quest gets auto-completed although I didn't even accept it nor see it.

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/42
