### ISSUE TITLE
An old history book item doesnt give quest

### ISSUE THREAD

**Issue by manuelinobdk** [SallyWhitemane/Herod#120]
**Description:** the book when it drops should be able to give u a quest that it doesnt

**How to reproduce:** get the item from a mob in duskwood

**How it should work:**should give u a quest
![Desktop Screenshot 2021 04 13 - 11 33 35 76](https://user-images.githubusercontent.com/82398722/114532613-4a6cef00-9c4d-11eb-96f0-1e8bbe78c0e9.png)

**Comment by HerodDev** [comment]
It shouldn't, quest is deprecated but item still is available to loot - all blizzlike
