### ISSUE TITLE
Venom web spider doesnt appear as quest mob

### ISSUE THREAD

**Issue by manuelinobdk** [SallyWhitemane/Herod#121]
**Description:**
when u get the quest dusky crab cakes the spiders supposed to give u the items dont appear as quest mobs

**How to reproduce:** accept the quest

**How it should work:**
the mobs should show up as quest mobs 
![Desktop Screenshot 2021 04 13 - 11 33 54 51](https://user-images.githubusercontent.com/82398722/114532930-a172c400-9c4d-11eb-949e-7cd8a308296d.png)

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26623/dusky-crab-cakes

**Comment by HerodDev** [comment]
fixed rev 17
