### ISSUE TITLE
Foulwead Furbolgs Don't Attack

### ISSUE THREAD

**Issue by Gaugeoak** [SallyWhitemane/Herod#125]
**Description:**
Foulwead Furbolgs in Greenpaw Village in Ashenvale don't attack..  They do put me in combat and constantly cast Corrupted Strength disease, but don't hit back.

**How to reproduce:**
Fighting them
![WoWScrnShot_041321_055824](https://user-images.githubusercontent.com/82425397/114542707-db2bd680-9c1d-11eb-9cc2-74ee56ca960f.jpg)

**How it should work:**
When I engage in combat they should hit me back for damage

**Comment by HerodDev** [comment]
fixed rev 17
