### ISSUE TITLE
Caravan from Silverwind Refuge to Stonetalon Through Earth

### ISSUE THREAD

**Issue by Gaugeoak** [SallyWhitemane/Herod#127]
**Description:**
When taking the caravan from Silverwind to Stonetalon, the slowly goes into the ground and underground.  Once I arrive to my destination, I fall far into the earth and die with no ability to even release to ghost form

**How to reproduce:**
Click on Caravan to begin the ride

**How it should work:**
Should ride above ground to my destination in Stonetalon
![WoWScrnShot_041321_064451](https://user-images.githubusercontent.com/82425397/114547490-1df0ad00-9c24-11eb-8388-a5e583af3031.jpg)
![WoWScrnShot_041321_064459](https://user-images.githubusercontent.com/82425397/114547506-234df780-9c24-11eb-9f75-cc02294e311f.jpg)

**Comment by HerodDev** [comment]
fixed rev 17
