### ISSUE TITLE
Quest A Revenant's Vengenace

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Herod#128]
**Description:**
https://www.wowhead.com/quest=14284/a-revenants-vengeance
Unless you get higher level(by a lot!) this quest is not completeable. In quest you're supposed to mount Lord Hydronis and battle Valishj. You can mount that elemental and it uses some spells at the beginning, but after using them in short time, he suddenly can't use them. From time to time he is able after using block but later on it wasn't even possible to use block. Also, hp and mana bar of Hydronis doesn't change, it shows he has full mana full hp while i can't use a spell and i don't have any notification about why can't i use spell. Also, he can't even auto attack, while auto attack is his main damage source.

**How to reproduce:**
take A revenant's Vengeance quest -> mount Lord Hydronis -> try to kill Valishj using his spells -> watch mana/hp bar

**How it should work:**

Lord Hydronis should be more responsive and interactive when it comes to fighting, he needs to be able to auto attack most of all and to complete quest. https://www.youtube.com/watch?v=uzDW92YQoR4

**Comment by HerodDev** [comment]
fixed rev 17
