### ISSUE TITLE
Quest: Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by asbj0510** [SallyWhitemane/Herod#129]
**Description:**
When you accept the quest a kodo is supposed to appear, but it doesn't. 

**How to reproduce:**
Accept the quest and you see nothing happens.

**How it should work:**
When you accept the quest a kodo is supposed to appear and you're supposed to click. 
Reference: https://www.youtube.com/watch?v=LSXvGXA6ovY

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/34
