### ISSUE TITLE
Quest: In Defense of Far Watch

### ISSUE THREAD

**Issue by asbj0510** [SallyWhitemane/Herod#130]
**Description:**
You kill 8x Razormane Water Seeker and 3x Razormane Hunter, but when you kill the Razormane Hunters it doesn't count towards completion. You see 1/3 Razormane Hunter Slain in the middle of your screen, but when you look under tracking nothing happens. And now you can't complete the quest because it doesn't count towards the completion. Tried it on two different characters.

**How to reproduce:**
Accept the quest and go kill Razormane Hunters and you see nothing happens under quest tracking.

**How it should work:**
Any kills should count towards the progression of the quest.

**Comment by HerodDev** [comment]
fixed in rev 15
