### ISSUE TITLE
[Quest] We´re under Attack

### ISSUE THREAD

**Issue by HoneyBelly** [SallyWhitemane/Herod#131]
**Description:**
https://www.wowhead.com/quest=27857/were-under-attack
https://www.wowhead.com/npc=46869/marshtide-invader
After some time looking for the mobs (Marshtide Invader) didn´t found even one.

**How to reproduce:**
Accept quest an looking for these mobs.

**How it should work:**
They should be in the wall from Stonard

**Comment by HerodDev** [comment]
fixed rev 17
