### ISSUE TITLE
[Quests] Hellscream's Legacy ID: 25616 - Broken

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#132]
**Description:** 
https://www.wowhead.com/quest=25616/hellscreams-legacy
Killing the canister on the back of the npcs doesnt explode

**How to reproduce:** 
Destroy a canister on the back of the npcs

**How it should work:** 
Canisters should explode stun and damage the ones that wears them.

**Comment by HerodDev** [comment]
fixed rev 17
