### ISSUE TITLE
[QUEST] 13975 Crossroads Caravan Delivery not startable

### ISSUE THREAD

**Issue by reknov** [SallyWhitemane/Herod#138]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:** The gossip option to start the quest does not exist

**How to reproduce:** Pick up the quest and try to start the event, maybe because someone else has done it earlier and the caravan does not "exist"

**How it should work:** There should be an gossip option on the NPC to start it

![WoWScrnShot_041321_221424](https://user-images.githubusercontent.com/82418787/114608170-107c0700-9ca6-11eb-98b2-59431ededdf4.jpg)
![WoWScrnShot_041321_221430](https://user-images.githubusercontent.com/82418787/114608183-12de6100-9ca6-11eb-9180-dd5db9311a7c.jpg)

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/34
