### ISSUE TITLE
Gidwin's Fate Revealed

### ISSUE THREAD

**Issue by RiasxWhitemane** [SallyWhitemane/Herod#139]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://www.wowhead.com/quest=27526/gidwins-fate-revealed
When you walk into the Slaughterhouse, supposed to trigger a cutscene which plays out

**How to reproduce:**
Walk into Slaughterhouse

**How it should work:**
https://www.youtube.com/watch?v=WnX6qGEwp3E

**Comment by SallyWhitemane** [comment]
Fixed in rev 28.
