### ISSUE TITLE
Jack "All-Trades" Derrington - Profession Trainer

### ISSUE THREAD

**Issue by RiasxWhitemane** [SallyWhitemane/Herod#14]
**Description:**
Unable to select gathering or crafting profession from Jack "All-Trades" Derrington

**How to reproduce:**
Speak to NPC.

**How it should work:**
Should be able to train from NPC.

**Comment by RiasxWhitemane** [comment]
https://wowwiki-archive.fandom.com/wiki/Jack_%22All-Trades%22_Derrington

**Comment by RiasxWhitemane** [comment]
Jack "All-Trades" Derrington still unable to interact with in Stormglen as well as Duskhaven

**Comment by IamNylea** [comment]
The same issue is with KTC Train-a-Tron Deluxe located in The Lost Isles and Azshara.
https://www.wowhead.com/npc=49885/ktc-train-a-tron-deluxe
https://www.wowhead.com/npc=45286/ktc-train-a-tron-deluxe

**Comment by HerodDev** [comment]
fixed rev 7
