### ISSUE TITLE
"zen'kiki the druid"

### ISSUE THREAD

**Issue by Jwulfgamingtv** [SallyWhitemane/Herod#140]
**Description:**
https://www.wowhead.com/quest=26953/zenkiki-the-druid
Quest "zen'kiki the druid" does not let you respawn the npc that you need to complete the quest when "seperated"

**How to reproduce:**
Took LFG que. After dungeon when i try to talk to quest giver it does not respawn zen'kiki

**How it should work:**
should be able to respawn zen'kiki when talking to quest giver npc

**Comment by HerodDev** [comment]
fixed rev 17
