### ISSUE TITLE
[NODE] Mining node underground Northern Barrens

### ISSUE THREAD

**Issue by reknov** [SallyWhitemane/Herod#141]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:** A mining node showing up on minimap in the very southern part of Northern Barrens, by the raptor nests

**How to reproduce:** Look for the node

**How it should work:** Should not be underground
![WoWScrnShot_041321_232218](https://user-images.githubusercontent.com/82418787/114616184-3eb21480-9caf-11eb-8bf1-379f5a4960c3.jpg)
![WoWScrnShot_041321_232146](https://user-images.githubusercontent.com/82418787/114616189-407bd800-9caf-11eb-9da6-e5aa0696c6af.jpg)

**Comment by HerodDev** [comment]
fixed rev 17
