### ISSUE TITLE
[QUEST] The battle for Andorhal - ID = 28750

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#142]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)
https://www.wowhead.com/quest=28750/the-battle-for-andorhal

**Description:**
Arcanist Arman doesn't teleport us to Andorhal, we can't talk to him.

**How to reproduce:**

**How it should work:**
He should be able to teleport us when we talk to him

**Comment by Zarke1408** [comment]
Arcanist Arman
https://www.wowhead.com/npc=49636/arcanist-arman

**Comment by HerodDev** [comment]
fixed rev 17
