### ISSUE TITLE
[QUEST] Scholomancer - 26924

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#143]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)
https://www.wowhead.com/quest=26924/scholomancer

**Description:**
Thassarian and Koltira spawn and Thassarian kill me before complete the quest. They fight among themselves, this is not normal

**How to reproduce:**

**How it should work:**
He shouldn't be fighting with each other, they should help us finish the boss and then allow us to return the quest without killing us :)

**Comment by HerodDev** [comment]
fixed rev 17
