### ISSUE TITLE
Lunk's Adventure: Cranky Little Dwarfs

### ISSUE THREAD

**Issue by RiasxWhitemane** [SallyWhitemane/Herod#144]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://www.wowhead.com/quest=27983/lunks-adventure-cranky-little-dwarfs
When Dark Iron Steamsmiths are lowered to a certain hp threshold lunk is supposed to put them to sleep

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=3uGjsTbrr-8

**Comment by HerodDev1** [comment]
Fixed in rev 20.
