### ISSUE TITLE
[Quest] All the quests in the "hunting" quest chain in Stranglethorn should be able to be handed in from anywhere

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#145]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:** 
As said in the title the whole quest chain should be able to be accepted anywhere after finishing the previous quest. like in here https://youtu.be/qG6VW_iDxqo?t=234

https://www.wowhead.com/quest=185/tiger-hunting

**How to reproduce:**
Finish the first quest in the chain and you dont get the complete notification.

**How it should work:** 
you should be able to accept the next quest in the chain from anywhere after finishing the previous one

**Comment by HerodDev** [comment]
fixed rev 17
