### ISSUE TITLE
[Quest] High Priestess Jeklik 

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#148]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**https://www.wowhead.com/quest=26553/high-priestess-jeklik

 This quest is totally broken, too much to explain none of the scripting works and after finishing it the follow up quest https://www.wowhead.com/quest=26554/plunging-into-zulgurub doesnt become avaible.

**How to reproduce:**

**How it should work:** https://www.youtube.com/watch?v=cE8hbHWkU-g

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/42
