### ISSUE TITLE
[Quest] Coaxing the Spirits

### ISSUE THREAD

**Issue by llogan1233** [SallyWhitemane/Herod#149]
https://www.wowhead.com/quest=13547/coaxing-the-spirits

**Description:**
When you interact with the dead NPCs their options don't do anything and it don't give you credit for the quest.

**How to reproduce:**
Talk to the quest NPCs and try to click the dialogue option

**How it should work:**
https://www.youtube.com/watch?v=_uwtBS1y49o&t=8s

**Comment by HerodDev** [comment]
fixed rev 17
