### ISSUE TITLE
[Quest] Lou´s Parting Thoughts

### ISSUE THREAD

**Issue by Jaydoc1234** [SallyWhitemane/Herod#15]
**Description:**
The 4 NPCs for the quest that u have to kill only spawn if u run on their spawn position.

**How to reproduce:**
Start the quest and u wont see the Mobs until u stay right on their spawn.

**How it should work:**
Normally after starting the quest the mobs should be spawned already.

https://www.wowhead.com/quest=26232/lous-parting-thoughts

**Comment by HerodDev** [comment]
more bugs in:
https://github.com/SallyWhitemane/Herod/issues/378
copied description
