### ISSUE TITLE
[QUEST] Rite of Vision - Pathing takes you under the world

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#152]
https://www.wowhead.com/quest=20441/rite-of-vision

**Description:**
Pathing as the Ghost Wolf takes you under the world. This is a graphical issue, as you do not fall, you merely continue pathing. Additionally, the ghost wolf form does not take you fully to the destination.

**How to reproduce:**
Accept quest Rite of Vision, use quest item. Observe pathing.

**How it should work:**
Ghost Wolf form should maintain footing on the ground throughout pathing.

**Comment by HerodDev** [comment]
fixed rev 17
