### ISSUE TITLE
Stranglethorn Fever quest bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#154]
**Description:**
In the quest Stranglethorn Fever, when you start the quest at the npc, the Mokk gorilla spawn instantly next to the npc. even though the gorillas should spawn in waves, and the last wave would be Mokk
https://www.wowhead.com/quest=26597/stranglethorn-fever
**How to reproduce:**
Kill gorillas in STV, get gorilla fang from them, talk to the npc called : Witch doctor Unbagwa, 
He will instantly summon Mokk.

**How it should work:**
Like in this video, a different types of gorillas should appear first, and then after them Mokk.
https://www.youtube.com/watch?time_continue=178&v=1ynPlqsjlLo&feature=emb_logo

**Comment by HerodDev** [comment]
fixed rev 17
