### ISSUE TITLE
The heart of the matter

### ISSUE THREAD

**Issue by Pallaladin** [SallyWhitemane/Herod#155]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

https://www.wowhead.com/quest=28484/the-heart-of-the-matter

**Description:**

Cave yeti does loot the heart but ingame tooltip do not tell us they do

**How to reproduce:**

accept the quest then go kill cave yeti, when you put your cursor on the yeti the tooltip should say 

**How it should work:**

when you put your cursor on the yeti the tooltip should say 
The Heart of the Matter
- Beating yeti heart: x/12
x is number of your heart already loot

**Comment by HerodDev** [comment]
fixed in rev 36
