### ISSUE TITLE
[Quest] This Means War ( Wild Arachnid Roundup)

### ISSUE THREAD

**Issue by xcenon92** [SallyWhitemane/Herod#156]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Its possible to only send one spider at a time to the Npcs because they dont one shot them and the Spiders go through the ground 

**How to reproduce:**
Accept the Quest get on to the mount and send the Spiders to the Hearthglen Recruits 

**How it should work:**

Normally you can send like more than one spider at the time to the Recruits and get it done faster and they should not go directely to the Recruits they should more like go into the direction your looking at and they should walk a bit more faster 

https://www.youtube.com/watch?v=41KqwEhDgIM
https://www.wowhead.com/quest=27001/this-means-war-wild-arachnid-roundup

**Comment by HerodDev** [comment]
fixed in rev 36
