### ISSUE TITLE
[Quest] It´s About Time 

### ISSUE THREAD

**Issue by xcenon92** [SallyWhitemane/Herod#158]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://www.wowhead.com/quest=27156/its-about-time
You can kill the NPC´s 

**How to reproduce:**
Accept the quest talk to the npc you´r about to duel and fight him 

**How it should work:**
After defeating the new Hearthglen Trainees in a mighty battle of life and death , they just should walk back to the puppet some do walk back but some you can kill if you overkill them

**Comment by HerodDev** [comment]
fixed in rev 36
