### ISSUE TITLE
[Quest]  [Ongo'longo's Revenge]

### ISSUE THREAD

**Issue by Allation2** [SallyWhitemane/Herod#161]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest dont complete when you attacked Ongo longo, he runs away and stays in the gate instead of despawing.

**How to reproduce:**
Accept quest and attack ongo longo.

**How it should work:**

https://youtu.be/BhU2t0OVoT4?t=125                     time stamp 2:00 min

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26367/ongolongos-revenge

**Comment by HerodDev** [comment]
fixed in rev 36
