### ISSUE TITLE
[Quest] Just Encased Eastern Plaguelands 

### ISSUE THREAD

**Issue by xcenon92** [SallyWhitemane/Herod#163]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The mobs for the Quest Just encased wont attack

**How to reproduce:**
Attack the Mobs 

**How it should work:**
They should attack you

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=27368/just-encased

**Comment by HerodDev** [comment]
fixed in rev 36
