### ISSUE TITLE
[Classtrainer] Warrior

### ISSUE THREAD

**Issue by HoneyBelly** [SallyWhitemane/Herod#167]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)
https://wowpedia.fandom.com/wiki/Yeniss

**Description:**
Yeniss (NOC) is in Sen´jin but not interactable.

**How to reproduce:**
Try to speak with the NPC in the bigges house in Sen´jin.

**How it should work:**
You should lern new Skills from him

**Comment by SallyWhitemane** [comment]
Fixed but Yeniss had wrong data (e.g name as Muradin Bronzebeard) in db so part of fix require deletion of Cache folder in order to properly show it's name in game.
