### ISSUE TITLE
[Quest] [Stopping Kuzen's Legacy]

### ISSUE THREAD

**Issue by mafa2** [SallyWhitemane/Herod#168]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Text bug with Chief Equivel, currently reads "By Kurzen s sword!"

**How to reproduce:**
Fight Chief Equivel

**How it should work:**
Text should read "By Kurzen's sword!"

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26737/stopping-kurzens-legacy

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
