### ISSUE TITLE
Can't Take it With Them Quest

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#171]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Swamp of Sorrows, the corpses dont spawn in the water, and they're only on land for some reason, they should all be in the water.

**How to reproduce:**

**How it should work:**
need corpses to be in the water not land.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=27599/cant-take-it-with-them

**Comment by HerodDev** [comment]
fixed in rev 36
