### ISSUE TITLE
Crypt walker mob bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#172]
**Description:**
The crypt walker undead spiders in the Terrorweb tunnel are bugged (like 70%of them) they are standing in one place, not attacking or moving.

**How to reproduce:**
Go to Terrorweb tunnel.
Attack the spiders.

**How it should work:**
They should be able to move and attack.
![WoWScrnShot_041421_184943](https://user-images.githubusercontent.com/58514021/114748836-981f4f80-9d52-11eb-847c-eb88c11d1c1f.jpg)
![WoWScrnShot_041421_184942](https://user-images.githubusercontent.com/58514021/114748841-98b7e600-9d52-11eb-8095-5193ac7bcdbc.jpg)

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/163
