### ISSUE TITLE
Zen'kiki, the druid quest

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#173]
**Description:**
https://www.wowhead.com/quest=26953/zenkiki-the-druid
In this quest you get a npc that follows you around helping with your quest.
It should despawn as soon as you leave the zone (Western Plaguelands)
But here this npc follows me to literally anywhere I go.

**How to reproduce:**
Do the Zen'kiki, the druid quest chain, and you will have him by your side even if you leave the zone.

**How it should work:**
It should disappear when you leave the zone.
![WoWScrnShot_041421_184943](https://user-images.githubusercontent.com/58514021/114749245-06641200-9d53-11eb-8e53-5cfb1d80b731.jpg)
![WoWScrnShot_041421_185001](https://user-images.githubusercontent.com/58514021/114749248-07953f00-9d53-11eb-83b3-3399b88eb4a5.jpg)

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
