### ISSUE TITLE
Pool of Tears

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#174]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Atal'ai Artifact don't give off nearly enough glowie light to be viewable in the murky water

**How to reproduce:**

**How it should work:**
sparkles should be bigger for so you can see the dark item in the dark water, in the dark dirt.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=1424/deprecated-pool-of-tears

**Comment by SallyWhitemane** [comment]
Shining effect is client side, we can only turn it on/off, rest is out of reach.
