### ISSUE TITLE
[QUEST] Combat Training -  26938

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#175]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)
https://www.wowhead.com/quest=26938/combat-training#

**Description:**
The mobs required for the quest are not spawn and we don't have the val'kyr pet bar available
I think the phasing isn't scripted

**How to reproduce:**

**How it should work:**
We should be able to use Val'kyr spells and mobs should be spawned

**Comment by HerodDev** [comment]
duplicate https://github.com/SallyWhitemane/Herod/issues/166
