### ISSUE TITLE
[QUEST] Lunk's Adventure: Cranky Little Dwarfs

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#177]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)
https://www.wowhead.com/quest=27983/lunks-adventure-cranky-little-dwarfs
https://www.youtube.com/watch?v=2M1e7AHGgsw (For explain)

**Description:**
Doesn't work, The NPC "Lunk" does nothing

**How to reproduce:**

**How it should work:**
He should jump on NPCs that have less than 50 percent health and put them to sleep.

**Comment by HerodDev1** [comment]
Fixed in rev 20.
