### ISSUE TITLE
[Miscellaneous] Chests - Food crate

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#179]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
We can't open the Chests or Food crate a little over the world or they do not contain anything (Azeroth)

**How to reproduce:**

**How it should work:**

**Comment by HerodDev** [comment]
Which client do you use? where did you get it from?

**Comment by Zarke1408** [comment]
I am using one of the client given on the discord
https://twinstar-wow.eu/files/WoW434_mini.zip
