### ISSUE TITLE
[Achievements] Ready, Set, Goat!

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#182]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
He doesn't work - Billy goat isn't counted
![WoWScrnShot_041421_203846](https://user-images.githubusercontent.com/82468604/114761996-82fded00-9d61-11eb-80cf-ae3e6da53469.jpg)

**How to reproduce:**

**How it should work:**
When we use the item on Billy Goat the achievement timer should start and the counter should increase by 1

**Wowhead links:**
https://www.wowhead.com/achievement=5444/ready-set-goat
https://www.wowhead.com/item=62397/billy-goat-blaster
https://www.wowhead.com/item=65898/billy-goat-blaster-dx
https://www.wowhead.com/npc=46393/billy-goat

**Comment by SallyWhitemane** [comment]
Fixed.
