### ISSUE TITLE
[NPC] Jessica Chambers <Inkeeper>

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#183]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
His option to bind my Heartstone doesn't work (I'm Blood Elf Paladin)
![WoWScrnShot_041421_205610](https://user-images.githubusercontent.com/82468604/114765010-efc6b680-9d64-11eb-9178-a6c17c2bfb82.jpg)
![WoWScrnShot_041421_205614](https://user-images.githubusercontent.com/82468604/114765026-f2291080-9d64-11eb-9f72-ba396e3b0456.jpg)

**How to reproduce:**

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/npc=16256/jessica-chambers

**Comment by HerodDev** [comment]
fixed in rev 7
