### ISSUE TITLE
[NPC] Provisioner Elda <Inkeeper>

### ISSUE THREAD

**Issue by Zarke1408** [SallyWhitemane/Herod#185]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
His options doesn't work

![WoWScrnShot_041421_210607](https://user-images.githubusercontent.com/82468604/114765363-5fd53c80-9d65-11eb-97ab-56b1a915a2f5.jpg)

**How to reproduce:**

**How it should work:**
We should be able to bind our hearthstone. And buy him 18 items

**Wowhead links:**
https://www.wowhead.com/npc=46271/provisioner-elda

**Comment by HerodDev** [comment]
fixed in rev 7
