### ISSUE TITLE
[QUEST] Waptor Twapping - Waptor Twap world object despawn timer very long

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#186]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The world objects spawned by the Waptor Twap item during the quest Waptor Twapping takes a very long time to despawn.

**How to reproduce:**
Lay a trap from the Waptor Twap item. Observe length of time for the trap to disappear. Anecdotally, I was able to turn in this quest and others in Ratchet, then return to kill additional mobs, and the traps were still present and trapping raptors.

**How it should work:**
Trap should despawn after a reasonable (1-2 minutes) amount of time.

**Wowhead links:**
https://www.wowhead.com/quest=14068/waptor-twapping

**Comment by HerodDev** [comment]
fixed in rev 36
