### ISSUE TITLE
[QUEST] Scholomancer ID: 26924 Broken

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#189]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
When Thassarian spawns near you when you take Darkmaster Gandling low he doesnt attack as he should

**How to reproduce:** 
do the quest

**How it should work:** 
Thassarian should attack Darkmaster Gandling after he teleports near you.

**Wowhead links:**
https://www.wowhead.com/quest=26924/scholomancer#comments

**Comment by HerodDev** [comment]
fixed in rev 17
