### ISSUE TITLE
Goblin Hot Rod

### ISSUE THREAD

**Issue by Turbocoom** [SallyWhitemane/Herod#19]
**Description:** 
Spawning the Goblin starter Hot Rod in some areas (door ways, inside) drops the vehicle on you,  you can proceed to spawn a fleet of hot rods.

**How to reproduce:**
Be a goblin, click Hot Rod key in a doorway or inside.

**How it should work:**
Previously spawned Hot Rod should dissapear/not spawn initially.
![WoWScrnShot_041121_162538](https://user-images.githubusercontent.com/82345768/114325068-f645fb80-9ae2-11eb-9fc2-ac90ced70ff1.jpg)

**Comment by HerodDev** [comment]
fixed rev 4
