### ISSUE TITLE
[NPC] Pilot Wizzlecrank

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#190]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest The Escape, Pilot Wizzlecrank exists his vehicle and spouts some lines. One of the lines uses the reference "$R", which fails.

![pwz0414](https://user-images.githubusercontent.com/82483575/114780112-95196480-9d3c-11eb-8a29-6b7ced967e36.png)

**How to reproduce:**
Complete the quest The Escape. When Pilot Wizzlecrank exits the shredder, he should say the line, with the incorrect reference.

**How it should work:**
His reference should reference something, and not appear as %R. Not exactly sure what it should be referencing, I can't identify a dialog list for this NPC.

**Wowhead links:**
https://www.wowhead.com/npc=3451/pilot-wizzlecrank
https://www.wowhead.com/quest=863/the-escape

**Comment by SallyWhitemane** [comment]
Fixed.
