### ISSUE TITLE
[Quest] Unusual Behavior... Even For Gnolls doesnt start automatically

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#197]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:** After finishing the previous quest in the chain which is Taelan Fordring's Legacy, you should be able to receive this quest automatically 

**How to reproduce:**

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/quest=27152/unusual-behavior-even-for-gnolls

**Comment by HerodDev1** [comment]
Fixed in rev 31.
