### ISSUE TITLE
Signs of the Legion broken

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#20]
**Description:** https://www.wowhead.com/quest=9594/signs-of-the-legion

You dont get the credit when killing the mobs. Both Satyr and Felsworn versions of the mob give you credit for Felsworn.
**How to reproduce:**

**How it should work:** Killing Nazzivus Satyr should should give credit for doing so.

**Comment by HerodDev** [comment]
Fixed in rev 5
