### ISSUE TITLE
[NPC] Orthus Cliffwalker and Helpless Young Druid - Should appear dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#204]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
According to quest text, Orthus Cliffwalker and the Helpless Young Druids in the room at the top of Thal'darah Grove should all be dead. Currently they are all quite alive:
![bag0417](https://user-images.githubusercontent.com/82483575/114809537-fc044100-9d6f-11eb-9c8f-4124612a21db.png)

**How to reproduce:**
Go to the room at the top of Thal'darah Grove in Stonetalon Mountains and observe the living NPCs

**How it should work:**
Orthus Cliff Walker and the surrounding Helpless Young Druids should be or appear to be dead:
![image](https://user-images.githubusercontent.com/82483575/114809657-3372ed80-9d70-11eb-937a-8836ef0f5802.png)

**Wowhead links:**
https://www.wowhead.com/npc=42091/orthus-cliffwalker
https://www.wowhead.com/npc=41528/helpless-young-druid

**Comment by HerodDev** [comment]
fixed in rev 7
