### ISSUE TITLE
[Rogue]

### ISSUE THREAD

**Issue by Renoucer** [SallyWhitemane/Herod#206]
Rogue Trainer in Booty Bay have wrong text.
![image](https://user-images.githubusercontent.com/82383779/114829062-ecfeac80-9dca-11eb-9634-49107f37b63a.png)

**Comment by Renoucer** [comment]
And I am Rogue ofc

**Comment by HerodDev** [comment]
Add link for wowhead

**Comment by Renoucer** [comment]
https://classic.wowhead.com/npc=1411/ian-strom#teaches-ability

**Comment by SallyWhitemane** [comment]
Fixed.
