### ISSUE TITLE
That's the End of that Raptor : Screamlash duplicate.

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#21]
**Description:**
2 Spawns of Screamlash, should only be one.

**Comment by HerodDev** [comment]
@PendingtonFlex Add wowhead links

**Comment by PendingtonFlex** [comment]
https://www.wowhead.com/quest=25195/thats-the-end-of-that-raptor
https://www.wowhead.com/npc=39385/screamslash

**Comment by HerodDev** [comment]
Fixed in rev 5
