### ISSUE TITLE
XP to ore collection

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#23]
**Description:**
XP from collecting mining isn't scaling properly.

**How to reproduce
I've mined from 9-13, each level it changes rapidly lowering the amount.
At level 13, the amount of XP is already 18 per node. It takes XP from 13-14 takes 11k.
**How it should work:**
I believe it scales off 2-4% of your XP based on your level of the skill, 4 - orange 3 - yellow 2 - green 0 - grey.
How the scaling is I'm not entirely sure, but I know it shouldn't be practically nothing at level 13.

**Comment by HerodDev** [comment]
duplicate,
better explanation: https://github.com/SallyWhitemane/Herod/issues/40
