### ISSUE TITLE
Hunter levelup lost resource 

### ISSUE THREAD

**Issue by Xenothang** [SallyWhitemane/Herod#243]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Hunters lose all focus on levelup

**How to reproduce:**
just levelup

**How it should work:**
Gives the player back full Focus on levelup

**Wowhead links:**

**Comment by SallyWhitemane** [comment]
Fixed.

**Comment by Jarvs97** [comment]
The problem of focus continues.

**Comment by Xenothang** [comment]
Problem still occurs
