### ISSUE TITLE
Elementals in Durotar.

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#25]
**Description:**
Elementals in Durotar, 40.30, 17.30.

Teeming Waterguard is supposed to be level 10.

Correction : 
Furious Earthguard + Teeming Waterguard should attacking eachother and be health gated at 90% till the player comes and kills them.

**Comment by PendingtonFlex** [comment]
Forgot to mention Furious Earthguard should also be level 10.

**Comment by HerodDev** [comment]
Fixed in rev 5
