### ISSUE TITLE
[GAMEOBJECT] Forge out of place in Orgrimmar

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#263]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There is a Forge gameobject in front of the Red Canyon Mining shop in the Valley of Honor in Orgrimmar, which should not be there.

**How to reproduce:**
Navigate to the Red Canyon Mining shop in the Valley of Honor, and observe the forge in front of the door.
![oop0416](https://user-images.githubusercontent.com/82483575/115093769-009c3700-9ee1-11eb-9263-0b099775658f.png)

**How it should work:**
This item should not be in this location, as shown in the picture below:
![image](https://user-images.githubusercontent.com/82483575/115093791-114cad00-9ee1-11eb-9e30-7233d80706cc.png)

**Wowhead links:**
https://wowpedia.fandom.com/wiki/Red_Canyon_Mining

**Comment by SallyWhitemane** [comment]
Fixed in rev 9.
