### ISSUE TITLE
[Quest] [Ashenvale] Gurtar's Request - No sparkly particals around objects

### ISSUE THREAD

**Issue by Lapaco94** [SallyWhitemane/Herod#275]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Pick 8 Thorned Bloodcup

**How to reproduce:**
Start quest, run around looking for flowers.
Find none because thise little buggers are pretty hard to find without sparkles.

**How it should work:**
See small sparkles to notify you of presence of this very pretty flower.

**Wowhead links:**
https://www.wowhead.com/quest=13875/gurtars-request

Screenshot from the flower zoomed in
![image](https://user-images.githubusercontent.com/82404667/115109927-ef066e00-9f78-11eb-9335-0d7b9b188d23.png)

Screenshot from the flower zoomed out
![image](https://user-images.githubusercontent.com/82404667/115109947-0a717900-9f79-11eb-9a96-b255de734633.png)

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
