### ISSUE TITLE
[Quest] Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#283]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
If you talk to Rocco Whipshank, he doesnt have a gossip menu to trigger the escort quest

**How to reproduce:**
complete prequest

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/quest=13975/crossroads-caravan-delivery

**Comment by Jarvs97** [comment]
How it should work:
Demonstrative video: [https://www.youtube.com/watch?v=x806X_oCs68](url)

**Comment by Keelyu** [comment]
I tried this, same result, no gossip menu

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/34
