### ISSUE TITLE
[NPC] Chonk - Missing <Innkeeper> tag

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#284]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Chonk NPC is an Innkeeper and does work as such, but is missing the tag in his name. He does appear when Track Innkeepers is used. According to comments on wowhead, this tag was added in 4.0.6
![cho0417](https://user-images.githubusercontent.com/82483575/115123344-347b6900-9f82-11eb-8c46-17deb7b4fba1.png)

**How to reproduce:**
Head to Stonemaul Hold, walk into the cave, and click on Chonk.

**How it should work:**
Supposedly according to wowhead comments, he should have an <Innkeeper> tag, however I am unable to find screenshot evidence of this.

**Wowhead links:**
https://www.wowhead.com/npc=44376/chonk

**Comment by HerodDev5** [comment]
Fixed in rev 38.
