### ISSUE TITLE
[Quest] Echeyakee

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#287]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
the mob doesn't need to be spawned

**How to reproduce:**

**How it should work:**
you need to blow the horn for him to appear

**Wowhead links:**
https://www.wowhead.com/npc=3475/echeyakee

**Comment by HerodDev5** [comment]
Fixed in rev 37
