### ISSUE TITLE
[GAMEOBJECT] Dire Maul Arena - Door prevents exit and cannot be interacted with or opened

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#295]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The exit to the Dire Maul Arena is blocked by a non-interact-able door. This door prevents exit from the Dire Maul Arena.
![dmd0417](https://user-images.githubusercontent.com/82483575/115128020-87641900-9fa0-11eb-8ee4-486145f8e774.png)

**How to reproduce:**
Enter the Dire Maul Arena. Attempt to leave. Your only exit will be blocked by a solid door which you cannot interact with.

**How it should work:**
There should be no door, or the door should be interact-able to open the door.

**Wowhead links:**

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
