### ISSUE TITLE
[NPC] Gordok Ogre-Mage - Bugged aggro dialogue

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#298]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Currently, when aggroed, Gordok Ogre-Mage's yell "Noooooooooooooooo!" each time they are aggroed. They should only yell this phrase when the Modified Soul Orb is used on them during the quest Ogre Abduction.
![gom0417](https://user-images.githubusercontent.com/82483575/115128998-8c789680-9fa7-11eb-8fb3-6752a1fbbd25.png)

**How to reproduce:**
Aggro Gordok Ogre-Mage NPCs in Dire Maul. Observe the aggro dialogue.

**How it should work:**
They should only use this phrase when the Modified Soul Orb is used on them during the quest Ogre Abduction. When aggroed, they should pull from the same Aggro dialogue table as the Gordok Enforcer NPCs.

**Wowhead links:**
https://www.wowhead.com/npc=11443/gordok-ogre-mage
https://www.wowhead.com/npc=11440/gordok-enforcer
https://www.wowhead.com/quest=25344/ogre-abduction

**Comment by HerodDev5** [comment]
Fixed in rev 37
