### ISSUE TITLE
[Druid] Quest Last Stand in Gilnea

### ISSUE THREAD

**Issue by xcenon92** [SallyWhitemane/Herod#3]
**Description:**
When you´start the quest Last stand the Mobs dont spawn in the Main Hall and the NPC kill the Mobs what they should not do 

**How to reproduce:**

Accept the Quest Last Stand 
**How it should work:**
https://www.youtube.com/watch?v=IYMX3V0apeA

**Comment by HerodDev** [comment]
fixed rev 4
