### ISSUE TITLE
[RARE NPC] Deathspeaker Selendre - Walks very fast

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#300]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Rare NPC Deathspeaker Selendre in Death's Step, Eastern Plaguelands walks very fast and does not stop walking when engaged in combat.
https://user-images.githubusercontent.com/82483575/115131317-d4ee7f00-9fbc-11eb-8381-3b04eb4851dd.mp4

**How to reproduce:**
Observe Deathspeaker Selendre as she walks around Death's Step. Optionally engage her in combat.

**How it should work:**
She should walk at a normal pace and should engage in combat when attacked, and not continue running.

**Wowhead links:**
https://www.wowhead.com/npc=10827/deathspeaker-selendre

**Comment by HerodDev5** [comment]
Fixed in rev 37
