### ISSUE TITLE
[QUEST] Just a Drop in the Bucket - Quest credit given immediately

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#304]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest credit for Just a Drop in the Bucket was given the moment I accepted the quest. This prevented the most fun part of this quest, overloading the cauldron.

**How to reproduce:**
Complete the quest Catalysm, remote turn-in, then receive Just a Drop in the Bucket.

**How it should work:**
The quest should not automatically award credit.

**Wowhead links:**
https://www.wowhead.com/quest=27453/catalysm
https://www.wowhead.com/quest=27454/just-a-drop-in-the-bucket

**Comment by HerodDev1** [comment]
Fixed in rev 31.
