### ISSUE TITLE
[GAMEOBJECT] Argent Lightwell - No limits to placement within Eastern Plaguelands

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#312]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Argent Lightwell spawned by the Argent Lightwell Charm received during the quest The Corpsebeasts has no limits on placements other than that it can only be used in the Eastern Plaguelands:

https://user-images.githubusercontent.com/82483575/115135933-df6f3f80-9fe1-11eb-9b9d-7474f44f188b.mp4

https://user-images.githubusercontent.com/82483575/115135936-e302c680-9fe1-11eb-9ef6-12500ac9298e.mp4

**How to reproduce:**
Obtain an Argent Lightwell Charm in Eastern Plaguelands and use the charm as many times as you wish, at any location within the Eastern Plaguelands.

**How it should work:**
The charm should only allow other charms to be placed more than 10 yards away.

**Wowhead links:**
https://www.wowhead.com/npc=45921/argent-lightwell
https://www.wowhead.com/item=61375/argent-lightwell-charm

**Comment by HerodDev** [comment]
Fixed in rev 5
