### ISSUE TITLE
Northern Barrens : Through Fire and Flames

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#32]
Needs quite the rework done. The rabbits are visible that allow the quest item to be clicked. All 3 wolves are missing, they're supposed to be in the stables then run out after you click the quest item.

**Comment by PendingtonFlex** [comment]
https://www.youtube.com/watch?v=c5zIo9oAojc

Added quest for admin reference.

**Comment by HerodDev** [comment]
fix in rev 10
