### ISSUE TITLE
The Seeds of Life

### ISSUE THREAD

**Issue by RiasxWhitemane** [SallyWhitemane/Herod#33]
**Description:**
Talk to Onu to receive Seed of Earth - Doesn't give seed.

**How to reproduce:**
Talk to Onu to get seed.

**How it should work:**

https://www.youtube.com/watch?v=NrL6mFk5HQw

**Comment by herodbetatester** [comment]
same for me

**Comment by HerodDev** [comment]
fixed in rev 10
