### ISSUE TITLE
[NPC] Tidal Strider

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#339]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Tidal Striders have Hunters Mark Debuff. 
![image](https://user-images.githubusercontent.com/47416114/115222733-548a6400-a10b-11eb-9db7-c65c3705592e.png)

**How to reproduce:**
Check over in Tanaris

Edit: After killing them, they don't respawn with the debuff. idk who put it on every single strider, there was no one around at this time

**How it should work:**
I'm sure they shouldn't have the debuff, atleast the attached wowhead screen shows different

**Wowhead links:**
https://www.wowhead.com/npc=39022/tidal-strider#comments
![image](https://user-images.githubusercontent.com/47416114/115222657-40466700-a10b-11eb-88ba-39ae3dbf3490.png)

**Comment by HerodDev5** [comment]
Fixed in rev 37
