### ISSUE TITLE
[NPC] Southsea Scoundrel / [Q] Seaside Salvage

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#340]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The NPC doesn't attack

**How to reproduce:**
loot some steamwheedle supplies for the quest "Seaside Salvage" 

**How it should work:**
they are aggressive against horde and alliance and should attack the player

**Wowhead links:**
https://www.wowhead.com/npc=40665/southsea-scoundrel
https://www.wowhead.com/quest=24906/seaside-salvage

**Comment by HerodDev5** [comment]
Fixed in rev 40.
