### ISSUE TITLE
[NPC] Southsea Strongarm [Skill] Impaling Pull

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#342]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The NPC uses his skill but it doesnt pull the player towards the npc

**How to reproduce:**
engage them in combat

**How it should work:**
Regarding the wowhead comments, they have something like a deathking deathgrip skill.

**Wowhead links:**
https://www.wowhead.com/npc=40635/southsea-strongarm#comments

**Comment by HerodDev5** [comment]
Fixed in rev 38.
