### ISSUE TITLE
[NPC] wrong spawns behind the Zul'Farak portal

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#347]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
these mobs don't belong in there
![image](https://user-images.githubusercontent.com/47416114/115239471-11d28700-a11f-11eb-8fd6-1735d548e0da.png)

**How to reproduce:**
tp to the instance entrance

**How it should work:**
Guess they have the wrong spawn point

**Wowhead links:**

**Comment by HerodDev5** [comment]
Fixed in rev 37
