### ISSUE TITLE
[Item] Fishing Lures

### ISSUE THREAD

**Issue by IamNylea** [SallyWhitemane/Herod#352]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Wrong duration of some lures. I checked:
>Shiny Bauble - it's correct 10min 
>Glass Fishing Bobber - 20 min (should be 10min)
>Nightcrawlers - 20 min (should be 10min)
>Bright Baubles - it's correct 10 min
>Aquadynamic Fish Attractor - 60 min (should be 10 min)

**How to reproduce:**
Buy lures or do some fishing dailies to acquire Glass Fishing Bobber. Use them and check what duration you get.

**How it should work:**
All of these lures should improve your fishing skill for 10 minutes.

**Wowhead links:**
https://wowpedia.fandom.com/wiki/Fishing_lure

**Comment by HerodDev5** [comment]
Fixed in rev 32
