### ISSUE TITLE
Gasbot go brrr

### ISSUE THREAD

**Issue by Turbocoom** [SallyWhitemane/Herod#36]
**Description:**
Gasbots can be spammed to produce many gasbots.

**How to reproduce:**
Click panel rapidly.

**How it should work:**
Gasbot limit.

**Comment by Turbocoom** [comment]
![WoWScrnShot_041121_203252](https://user-images.githubusercontent.com/82345768/114337092-5352a900-9b05-11eb-90f4-9291ce631033.jpg)

**Comment by Turbocoom** [comment]
![WoWScrnShot_041121_203252](https://user-images.githubusercontent.com/82345768/114337202-8eed7300-9b05-11eb-9844-8d5244ea42da.jpg)

**Comment by HerodDev** [comment]
fixed rev 4
