### ISSUE TITLE
[MODEL] Warp Storm - The Warp Fields - Model is of a Shade

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#361]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Warp Storms in The Warp Fields appear to be using the wrong model, that of a shade, shown below:
![twf0419](https://user-images.githubusercontent.com/82483575/115308845-012b0c80-a131-11eb-9a2d-9a1bb7b2a19e.png)

**How to reproduce:**
Navigate to The Warp Fields in Hellfire Peninsula, look for the Warp Storms.

**How it should work:**
They should appear as large (roughly 10 times the size of a tauren) warp storms, as below:
![image](https://user-images.githubusercontent.com/82483575/115309010-48b19880-a131-11eb-86f8-d6892996a8ef.png)

**Wowhead links:**
https://wowpedia.fandom.com/wiki/Warp_Fields

**Comment by HerodDev5** [comment]
Fixed in rev 38.
