### ISSUE TITLE
[GAMEOBJECT] Force Commander Gorax's Corpse - Shouldn't exist

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#363]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There is a red crystal hear Force Commander Gorax's spawn named Force Commander Gorax's Corpse. This crystal should not be here.
![gor0419](https://user-images.githubusercontent.com/82483575/115315267-91bb1a00-a13c-11eb-9eeb-92ac3656d59a.png)

**How to reproduce:**
Navigate to the Training area under Hellfire Citadel where Force Commnader Gorax spawns. Mouse over the Red crystal on the ground.

**How it should work:**
There should be no crystal here.

**Wowhead links:**

**Comment by HerodDev5** [comment]
Fixed in rev 37
