### ISSUE TITLE
[NPC] Magic Sucker Device Buttress - Is targetable, should not be

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#365]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Magic Sucker Device Buttress is targetable by the player, and should not be

![msd0419](https://user-images.githubusercontent.com/82483575/115316077-40138f00-a13e-11eb-8b30-f3ef2b26438e.png)

**How to reproduce:**
During the quest The Demoniac Scryer, use the Demoniac Scryer item as normal. As the event progresses, the Magic Sucker Device Buttress NPCs spawn, confirm that you can target them.

**How it should work:**
You should not be able to target these NPCs

**Wowhead links:**
https://www.wowhead.com/npc=22267/magic-sucker-device-buttress

**Comment by HerodDev5** [comment]
Fixed in rev 37
