### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Herod#368]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Tormentor are fearing themselves.

**How to reproduce:**
engage combat with a tormentor

**How it should work:**
they should put the fear on the player

**Wowhead links:**
https://www.wowhead.com/npc=19424/bleeding-hollow-tormentor

**Comment by HerodDev5** [comment]
Fixed in rev 37
