### ISSUE TITLE
It's Alive!  quest mobs take long time to respawn

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#38]
**Description:**
In this westfall quest:
https://wowpedia.fandom.com/wiki/It%27s_Alive!_(Westfall)
The mobs the amount of mobs you can kill on the field is around 20 , and after you kill them, you have to wait 15-20 minutes for them to respawn.
**How to reproduce:**
Jump in to the Overloaded harvest golem, kill all the mobs in the field next to it.

**How it should work:**
It should have more energized harvest golems you can kill, and they should respawn really fast.
Like in this video:
https://www.wowhead.com/quest=26257/its-alive#videos:id=90674

**Comment by HerodDev** [comment]
fixed rev 10
