### ISSUE TITLE
[QUEST] Summoner Kanthin's Prize - Quest item not 100% drop rate

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#380]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Summoner Kanthin does not drop the Stone of Glacius item 100% of the time. It took me 5 kills to get the item.

https://user-images.githubusercontent.com/82483575/115481381-1e83d780-a212-11eb-884c-b983a39367c3.mp4

**How to reproduce:**
Accept the quest Summoner Kanthin's Prize, kill Summoner Kanthin and loot his corpse. Observe drop rate.

**How it should work:**
The Stone of Glacius should have a 100% drop rate while on the quest.

**Wowhead links:**
https://www.wowhead.com/quest=10209/summoner-kanthins-prize

**Comment by HerodDev5** [comment]
Fixed in rev 37
