### ISSUE TITLE
Secrets of the Tower quest small bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#39]
**Description:**
In the quest westfall quest Secrets of the Towe, there are guards that are guarding the tower, you have to go into the tower and use the invisibility quest item , but before you go into the tower you have to get through the guards. Here the guards attack you, and you either have to kill them , which is not possible at this lvl, or rush into the tower and using the invisibility fast so you dont die.

**How to reproduce:**
Take quest :Secrets of the Tower, start going into the tower through the guards.

**How it should work:**
When the guards attack you the Quest giver npc should one shot them.
proof: https://www.youtube.com/watch?v=Mr29_ilHO7s&t=46s

**Comment by HerodDev** [comment]
fixed rev 10
