### ISSUE TITLE
Bloodelf Hunter Quest- Steady Shot

### ISSUE THREAD

**Issue by Alaeria-Val** [SallyWhitemane/Herod#4]
**Description:** At level 3, Ranger Sallina gives a quest "Steady Shot" that tells you to learn steadyshot and then use it 5 times on training dummies.  She gives the quest, but it disappears from her UI and becomes unable to turn in. 

**How to reproduce:**
Level a bloodelf hunter
Take her quest
Complete the quest
Notice you  can't turn in the quest. 

**How it should work:**
You get the quest, and shoot training dummies, return to her and turn the quest in.

**Comment by HerodDev** [comment]
It doesnt dissapear, you finish quest at 
https://www.wowhead.com/npc=15295/well-watcher-solanian
