### ISSUE TITLE
Xp from mining is bugged

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Herod#40]
**Description:**
Mining ores doesn't give enough/ doesnt give at all experience.

**How to reproduce:**
Mine copper on tin ore at lvl 18

**How it should work:**
it should give more experience according to this : https://wowwiki-archive.fandom.com/wiki/Formulas:Gather_XP
Also in this video a lvl 46 is mining a copper ore : https://www.youtube.com/watch?v=KC6PlHJy-aI
and it gives him 20 experience, even  though is higher lvl. While in my screenshots im lvl 18, and yet I got zero xp from copper , and 4 xp from tin vein.
edit: Also mining silver literally also gives 0 experience, even though my mining is at 74 rn. So it shows silver nodes as "red"

screenshots:
![WoWScrnShot_041221_090213](https://user-images.githubusercontent.com/58514021/114354063-0820b080-9b6e-11eb-855b-a70f789843c0.jpg)
![WoWScrnShot_041221_090040](https://user-images.githubusercontent.com/58514021/114354066-08b94700-9b6e-11eb-93cf-56e62294aa8e.jpg)
![WoWScrnShot_041221_090043](https://user-images.githubusercontent.com/58514021/114354067-08b94700-9b6e-11eb-81b5-52ed4dee8275.jpg)
![WoWScrnShot_041221_090202](https://user-images.githubusercontent.com/58514021/114354069-0951dd80-9b6e-11eb-8743-c3e18f47996d.jpg)
![WoWScrnShot_041221_091305](https://user-images.githubusercontent.com/58514021/114355059-52566180-9b6f-11eb-9323-658d927a7a29.jpg)

**Comment by HerodDev5** [comment]
Fixed in rev 26
