### ISSUE TITLE
[QUEST] Knee-Deep - Rats don't care about the player

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#400]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Knee-Deep, you need to run through a rat infested tunnel, using a torch to keep the rats at bay. Currently the rats do not care about your presence, and do not attack you.

https://user-images.githubusercontent.com/82483575/115635100-8862b680-a2d0-11eb-8334-8c494ba59ee8.mp4

**How to reproduce:**
Accept the quest Knee-Deep, and enter the tunnel.

**How it should work:**
The rats should attack you unless you use the Half-Burnt Torch item.

**Wowhead links:**
https://www.wowhead.com/quest=24678/knee-deep

**Comment by HerodDev1** [comment]
Fixed in rev 34.
