### ISSUE TITLE
[QUEST] Endgame - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#402]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Quest credit for Endgame is automatically awarded when the quest is accepted.

https://user-images.githubusercontent.com/82483575/115635839-39b61c00-a2d2-11eb-9f20-0a95a976dd27.mp4

**How to reproduce:**
Accept the quest Endgame from Lorna Crowley.

**How it should work:**
The quest should let you hop on the hippogryphs and complete the climactic final battle of the Gilnean starting zone.

**Wowhead links:**
https://www.wowhead.com/quest=26706/endgame

**Comment by HerodDev1** [comment]
Fixed in rev 33.
