### ISSUE TITLE
[QUEST] The Fight Continues - All text is errored out

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#403]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The entirety of the spoken conversation during the quest The Fight Continues is shown as <error>, as shown below:
![tfc0421](https://user-images.githubusercontent.com/82483575/115639243-b8628780-a2d9-11eb-9a51-1d551dab7fa3.png)

**How to reproduce:**
Accept the quest The Fight Continues and observe the conversation.

**How it should work:**
The dialog is listed in the wowpedia link.

**Wowhead links:**
https://www.wowhead.com/quest=26208/the-fight-continues
https://wowpedia.fandom.com/wiki/The_Fight_Continues

**Comment by HerodDev1** [comment]
Fixed in rev 31.
