### ISSUE TITLE
[QUEST] The Vengeance of Elune - Starfall special ability does not do damage

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#404]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest The Vengeance of Elune, special abilities are given to the player. One of these abilities is Starfall, which should deal damage to all enemies within 30 yards. Currently, this ability does nothing when used other than a visual effect.

https://user-images.githubusercontent.com/82483575/115779518-b6520480-a37d-11eb-90ab-9347200ecb44.mp4

**How to reproduce:**
Accept the quest The Vengeance of Elune. While in the special form, attempt to use Starfall near enemies. This may be affected by my cat form, so you may also need to test while in cat form.

**How it should work:**
Starfall should damage nearby enemies.

**Wowhead links:**
https://www.wowhead.com/quest=14005/the-vengeance-of-elune

**Comment by HerodDev1** [comment]
Fixed in rev 31.
