### ISSUE TITLE
[QUEST] Strategic Strikes - Line of sight issue.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#405]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Strategic Strikes, Lorenth Thundercall has strange line of sight issues, disallowing most of his "arena" from being used. You have to stand on a nearby log to hit him with the quest item.

**How to reproduce:**
Accept the quest Strategic Strikes and attempt to attack Lorenth Thundercall using the Dryad Spear item from the ground.

**How it should work:**
The ground near Lorenth Thundercall should be within line of sight of him.

**Wowhead links:**
https://www.wowhead.com/quest=13512/strategic-strikes

**Comment by HerodDev1** [comment]
Fixed in rev 31.
