### ISSUE TITLE
[Jewelcrafting] Brilliant glass

### ISSUE THREAD

**Issue by Allation2** [SallyWhitemane/Herod#406]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
if you right click the brilliant glass in your inventory there are no gems inside

**How to reproduce:**
craft a brilliant glass and use it

**How it should work:**
there should be gems in the brilliant glass

**Wowhead links:**

https://de.wowhead.com/item=35945/glänzendes-glas

**Comment by SallyWhitemane** [comment]
Item has loot assigned, friendly reminder there always is chance for item to simply not provide you loot (RNG doesn't have to reward it to you :P )
