### ISSUE TITLE
[Jewelcrafting]  Stone Statue

### ISSUE THREAD

**Issue by Allation2** [SallyWhitemane/Herod#407]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
the stonestues arent healing 

**How to reproduce:**
use a stone statue

**How it should work:**
they should be channeling a healing spell on you

**Wowhead links:**
https://de.wowhead.com/item=25498/raue-steinstatue
https://de.wowhead.com/item=25881/schwere-steinstatue
https://de.wowhead.com/item=25880/grobe-steinstatue
https://www.wowhead.com/item=25882/solid-stone-statue
https://de.wowhead.com/item=25883/verdichtete-steinstatue

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
