### ISSUE TITLE
Quest: Return of the bravo company (Redridge chain quest)

### ISSUE THREAD

**Issue by LukaszSzczygielski** [SallyWhitemane/Herod#409]
**Description:**
NPCs that we save during questing are doing nothing.
Even one of them bugs in fights (Jorgensen), is trying to cast a spell then instantly cancels it all the time.

**How to reproduce:**

Start quest line

**How it should work:**
They should help a player.

**Wowhead links:**
https://www.wowhead.com/quest=26563/return-of-the-bravo-company

![WoWScrnShot_042321_171718](https://user-images.githubusercontent.com/81674221/115893320-541a0200-a458-11eb-9c73-847dfc9fb6cc.jpg)

![WoWScrnShot_042321_172547](https://user-images.githubusercontent.com/81674221/115893925-005be880-a459-11eb-8e73-a2b128df645f.jpg)

**Comment by HerodDev1** [comment]
Fixed in rev 31.
