### ISSUE TITLE
[QUEST] A Curse We Cannot Lift - Lurking Worgen doesn't spawn

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#410]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest A Curse We Cannot Lift, a Lurking Worgen should spawn when you enter the barn in Addle's Stead. Currently, the Lurking Worgen does not spawn, so the quest is not completable.
![cur0423](https://user-images.githubusercontent.com/82483575/115897312-e4892000-a421-11eb-88af-96a0c821593f.png)

**How to reproduce:**
Accept the quest A Curse We Cannot Lift. Enter the Barn at Addle's Stead. Observe that the Lurking Worgen does not spawn.

**How it should work:**
The Lurking Worgen should spawn, which you will need to weaken and then use the quest item on.

**Wowhead links:**
https://www.wowhead.com/quest=26720/a-curse-we-cannot-lift

**Comment by Ahumaya** [comment]
He does spawn, but does not jump down.
![cur20423](https://user-images.githubusercontent.com/82483575/115897449-0da9b080-a422-11eb-8fe9-51416f095deb.png)

**Comment by HerodDev1** [comment]
Fixed in rev 31.
