### ISSUE TITLE
[QUEST] Raptor Mastery, Panther Mastery, Tiger Mastery - Not provided remotely

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#412]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The 3 quests, Raptor Mastery, Panther Mastery, and Tiger Mastery should be given after completing the related Prowess quests through the Remote Quest interface (the sidebar). Currently you need to go back to the Nesingwary encampment to pick up the mastery quests.
![mas0423](https://user-images.githubusercontent.com/82483575/115929668-cb966400-a44d-11eb-8846-8ac0d699e856.png)

**How to reproduce:**
Complete the Tiger, Panther, or Raptor Mastery quests using the sidebar.

**How it should work:**
The quests should be provided via the sidebar upon completing the Prowess versions.

**Wowhead links:**
https://www.wowhead.com/quest=187/tiger-prowess
https://www.wowhead.com/quest=192/panther-prowess
https://www.wowhead.com/quest=196/raptor-prowess
https://www.wowhead.com/quest=188/tiger-mastery
https://www.wowhead.com/quest=193/panther-mastery
https://www.wowhead.com/quest=197/raptor-mastery

**Comment by HerodDev1** [comment]
Fixed in rev 31.
