### ISSUE TITLE
[QUEST] Brute Strength - Thassarian and Koltira fight each other

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#416]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
After battling Darkmaster Gandling, Thassarian and Koltira spawn to battle Gandling with the player. Currently, Thassarian and Koltira battle each other.

**How to reproduce:**
Damage Darkmaster Gandling down to 0HP during the quest Brute Strength.

**How it should work:**
Koltira and Thassarian should meet in a wary truce.

**Wowhead links:**
https://www.wowhead.com/quest=27163/brute-strength

**Comment by HerodDev1** [comment]
I cannot reproduce on rev 27.

![image](https://user-images.githubusercontent.com/86661453/125340991-661e8900-e353-11eb-9442-67abfc3738ad.png)
