### ISSUE TITLE
[QUEST] A Different Approach - Birds are not flying above hill. Zen'Kiki is not needed to call them down

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#417]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest A Different Approach, the Diseased Hawks should circle above the hill to the East of The Mender's Stead. Zen'Kiki should have an interact option to attack one and bring it down close enough where the player can attack it. Currently, all the birds are standing on the ground on the hill, and Zen'Kiki can not be interacted with.
![ada0423](https://user-images.githubusercontent.com/82483575/115946928-133ae100-a48a-11eb-9213-1a35d12450be.png)

**How to reproduce:**
Attempt to complete A Different Approach.

**How it should work:**
The Diseased Hawks should be flying above the hill. Zen'Kiki should have an interact option to attack the birds.

**Wowhead links:**
https://www.wowhead.com/quest=26954/a-different-approach

**Comment by HerodDev1** [comment]
Fixed in rev 31.
