### ISSUE TITLE
[QUEST] Ashes to Ashes AND Supporting the Troops - Quests are mutually exclusive

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#418]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quests Ashes to Ashes and Supporting the Troops are offered in Andorhal by Thassarian and Lang Loosegrip respectively. Currently, they are both offered at the same time, but if either is accepted, the other disappears. Please see the video.

https://user-images.githubusercontent.com/82483575/115947207-bb9d7500-a48b-11eb-88a9-a958438ea6f1.mp4

**How to reproduce:**
Accept either Ashes to Ashes OR Supporting the Troops while both are available. Observe as the quest marker for the other quest disappears.

**How it should work:**
Both quests should be able to be taken at the same time.

**Wowhead links:**
https://www.wowhead.com/quest=27199/ashes-to-ashes
https://www.wowhead.com/quest=27198/supporting-the-troops

**Comment by HerodDev1** [comment]
Fixed in rev 31.

**Comment by mserkanoz** [comment]
I have the both quests but they don't work.
