### ISSUE TITLE
[Quest] - Pirate Accuracy Increasing (bugged)

### ISSUE THREAD

**Issue by LukaszSzczygielski** [SallyWhitemane/Herod#419]
**Description:**
Fire on boat can't be put out using boat from quest

**How to reproduce:**
Start quest, get on the boat and try to pyt fire out.

**How it should work:**
Boat should work properly.

**Wowhead links:**
https://www.wowhead.com/quest=25533/pirate-accuracy-increasing

![WoWScrnShot_042421_164617](https://user-images.githubusercontent.com/81674221/115962743-1501b480-a51d-11eb-930f-2360bf2f2668.jpg)

**Comment by HerodDev1** [comment]
I can't reproduce on rev 27.

![image](https://user-images.githubusercontent.com/86661453/125293068-5be49680-e323-11eb-94a6-62f2e7baffaa.png)
