### ISSUE TITLE
[QUEST] The Good People of Hearthglen - Is not given remotely

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#421]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The next quest in the series after the report in #197 this quest is not given remotely either.

**How to reproduce:**
Complete the quest Unusual Behavior... Even For Gnolls, you should receive this quest remotely.

**How it should work:**
After completing Unusual Behavior... Even For Gnolls, you should automatically receive The Good People of Hearthglen remotely.

**Wowhead links:**
https://www.wowhead.com/quest=27153/the-good-people-of-hearthglen
https://www.wowhead.com/quest=27152/unusual-behavior-even-for-gnolls

**Comment by Ahumaya** [comment]
Bagging Bisp is also affected
https://www.wowhead.com/quest=27154/bagging-bisp

**Comment by Ahumaya** [comment]
Turning Yourself In is also affected
https://www.wowhead.com/quest=27155/turning-yourself-in

**Comment by Ahumaya** [comment]
Students of Krastinov is also affected
https://www.wowhead.com/quest=27055/students-of-krastinov

**Comment by HerodDev1** [comment]
Fixed in rev 31.
