### ISSUE TITLE
[QUEST] Return to the Stead - Allows you to turn in to the Cauldron

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#422]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest Return to the Stead is allowing you to turn the quest in at the Scourge Cauldron in Gahrron's Withering. It should only allow you to turn it in to Field Agent Kaartish.
![rtt0424](https://user-images.githubusercontent.com/82483575/115967237-0f917380-a4f7-11eb-8388-bf2ecda26c4a.png)

**How to reproduce:**
Accept the quest Return to the Stead from the Scourge Cauldron. Observe that you can turn the quest in to the Scourge Cauldron immediately.

**How it should work:**
The Scourge Cauldron should not have the ability to turn the quest Return to the Stead in.

**Wowhead links:**
https://www.wowhead.com/quest=27057/return-to-the-stead

**Comment by HerodDev1** [comment]
Fixed in rev 31.
