### ISSUE TITLE
[NPC] Ursius - Spawns in Tanaris, falls from the sky

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#423]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Ursius spawns well above the player and falls down into the Tanaris bay, visible while in the Hot Air Balloon during Rocket Rescue. Ursius should be in Winterspring.

https://user-images.githubusercontent.com/82483575/115974064-9fe3ae80-a51f-11eb-8538-680f513308b3.mp4

**How to reproduce:**
Accept the quest Rocket Rescue, board the Hot Air Balloon, and watch around the balloon as you fly around. I was able to witness it a second time to record the video above.

**How it should work:**
Ursius should not spawn in Tanaris.

**Wowhead links:**
https://www.wowhead.com/npc=10806/ursius
https://www.wowhead.com/quest=25050/rocket-rescue

**Comment by HerodDev1** [comment]
Fixed in rev 31.
