### ISSUE TITLE
[ITEM] Butcherbot Contorl Gizmo - Can summon multiple Butcherbots

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#424]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Butcherbot Control Gizmo can summon multiple Butcherbots, shown in the screenshot below.
![but0424](https://user-images.githubusercontent.com/82483575/115974212-ce15be00-a520-11eb-8f3c-276040296d55.png)

**How to reproduce:**
During any Butcherbot quest, such as Scavengers Scavenged, use the Butcherbot Control Gizmo as many times as you like.

**How it should work:**
Only one Butcherbot should be able to be summoned at a time.

**Wowhead links:**
https://www.wowhead.com/item=52715/butcherbot-control-gizmo
https://www.wowhead.com/quest=25111/scavengers-scavenged
https://www.wowhead.com/npc=39696/butcherbot

**Comment by HerodDev** [comment]
Fixed rev 6
