### ISSUE TITLE
[NPC] Burning Corpses in Lost Rigger Cove - Untargettable, on fire, and apparently alive

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#425]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
I can't find a wowhead link for these NPCs, as they are untargettable, but in Lost Rigger Cove, these NPCs are on-fire and appear to be alive, but should be dead.

https://user-images.githubusercontent.com/82483575/115974579-5c8b3f00-a523-11eb-935f-2a38a5ab2be4.mp4

**How to reproduce:**
Observe the burning NPCs in Lost Rigger Cove.

**How it should work:**
The NPCs should appear to be dead.

**Wowhead links:**

**Comment by HerodDev5** [comment]
Fixed in rev 45.
