### ISSUE TITLE
[PHASING] Glory Amidst Chaos - Enemies are not present in phase. Relog fixes

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#428]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
After accepting the quest Glory Amidst Chaos, the phase did not have the enemy NPCs to kill. A relog placed me high in the air above the mountain, killing me, but put me in the correct phase and I was able to find and kill the enemies.

**How to reproduce:**
Complete Assault on Dreadmaul Rock and then pick up Glory Amidst Chaos. Head towards Dreadmaul Rock, and note that there are no enemies, and the Quest NPCs are not there. A relog fixes.

**How it should work:**
On accepting the quest Glory Amidst Chaos, you should be immediately placed in the correct phase for the quest.

**Wowhead links:**
https://www.wowhead.com/quest=28321/glory-amidst-chaos

**Comment by HerodDev1** [comment]
![image](https://user-images.githubusercontent.com/86661453/125064412-eec9ca80-e0b0-11eb-91de-c558f192fc4b.png)

I cannot reproduce that on rev 25.

You are in phase: 346 Assault Dreadmaulrock 2, which is correct one.
