### ISSUE TITLE
[NPC] Green Dragons in The Butchery in Temple of Atal'Hakkar - Should appear dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#430]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There are many Green Dragon models in The Butchery in the Temple of Atal'Hakkar (not the dungeon). I can not find the wowhead link for these NPCs. Please see the attached screenshot below:
![atl0424](https://user-images.githubusercontent.com/82483575/115979895-3333d880-a54e-11eb-8b1d-b926a279a511.png)

**How to reproduce:**
Enter The Butchery within the Temple of Atal'Hakkar. Observe the living, flying, untargettable Green Dragons.

**How it should work:**
The Green Dragon models should appear to be dead, as in the background of this image:
![image](https://user-images.githubusercontent.com/82483575/115979879-1b5c5480-a54e-11eb-8a0f-59cae1e90c33.png)

**Wowhead links:**
https://www.wowhead.com/npc=46623/gomora-the-bloodletter

**Comment by HerodDev5** [comment]
Fix in rev 45.
