### ISSUE TITLE
[QUEST] Blessing of the Green Dragonflight - Not given remotely

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#431]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
After completing the quest Step Three: Prophet, the next quest Blessing of the Green Dragonflight is not provided remotely via the sidebar.

**How to reproduce:**
Complete the quest Step Three: Prophet in the Temple of Atal'Hakkar. Observe that you do not get the next quest.

**How it should work:**
After completing Step Three: Prophet, you should remotely receive this quest, Blessing of the Green Dragonflight.

**Wowhead links:**
https://www.wowhead.com/quest=27914/blessing-of-the-green-dragonflight
https://www.wowhead.com/quest=27773/step-three-prophet

**Comment by HerodDev1** [comment]
Fixed in rev 22.
