### ISSUE TITLE
[QUEST] A Closer Look - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#432]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest credit for A Closer Look is automatically awarded when accepted from Enohar Thunderbrew.

https://user-images.githubusercontent.com/82483575/115981682-249fee00-a55b-11eb-958d-eb6b180020ab.mp4

**How to reproduce:**
Accept the quest A Closer Look from Enohar Thunderbrew in Nethergarde Keep

**How it should work:**
The quest credit should not be awarded immediately, the player should need to investigate the quest area.

**Wowhead links:**
https://www.wowhead.com/quest=25715/a-closer-look

**Comment by HerodDev1** [comment]
Fixed in rev 22.
