### ISSUE TITLE
[Quest item]  Slitherblade Charm - Quest name: Wetter than wet - Zone: Desolace

### ISSUE THREAD

**Issue by Kevingox4** [SallyWhitemane/Herod#433]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
when you use the item you turn into a naga and the ability bar changes 
but when I cast anything from that bar it cancels the transformation and when I kill the quest mob without the transformation 
it doesn't count

**How to reproduce:**
Accept the quest --> use the quest item --> Try using an ability

**How it should work:**
it shouldn't transform the player back and stay in Naga form when you cast the given spells

**Wowhead links:**
https://www.wowhead.com/quest=14264/wetter-than-wet
https://www.wowhead.com/item=49088/slitherblade-trident

**Comment by HerodDev1** [comment]
![image](https://user-images.githubusercontent.com/86661453/125063129-6696f580-e0af-11eb-9314-d4a4d038abdf.png)


I cannot reproduce it on rev 25. I have used any spell that I have in spell bar. Still in form.
