### ISSUE TITLE
[QUEST] The Altar of Storms - All enemies spawn at once

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#434]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest The Altar of Storms, you need to defend Loramus' Body from waves of enemies. Currently, 1 enemy spawns first, then all other enemies spawn at the same time with the second wave.

**How to reproduce:**
With the quest The Altar of Storms, head to the Altar of Storms and interact with the Altar. Observe as waves spawn. 1 imp will spawn in the first wave, and all other enemies will spawn in the second wave.

**How it should work:**
Each wave should be a smaller amount of enemies, and there should be several waves.

**Wowhead links:**
https://www.wowhead.com/quest=26162/the-altar-of-storms

**Comment by HerodDev1** [comment]
Fixed in rev 27.
