### ISSUE TITLE
(QUEST) - From The Shadows (WORGEN Tutorial)

### ISSUE THREAD

**Issue by Darkkob** [SallyWhitemane/Herod#436]
**Description:**
When you Summon The Gilnean Mastiff and hes killed by The Worgen mobs you Remain in Combat, which then makes it impossible to get out of Combat or be able to summon him again, you are then forced to alt + f4 and relog back.

**How to reproduce:**
Let the Mastiff die.

**How it should work:**
When the mastiff dies and you kill the mob which was Attacking your Mastiff, it should bring you out of Combat so you can summon it again.

**Wowhead links:**
https://www.wowhead.com/quest=14204/from-the-shadows
https://www.wowhead.com/item=48707/gilnean-mastiff-collar (SUMMON) (QUEST ITEM)

**Comment by HerodDev1** [comment]
I cannot reproduce that on rev 25. When mastiff dies,the worgen will take player as a next target. When you kill worgen, player stays out of combat.
