### ISSUE TITLE
[QUEST] - Last Stand (WORGEN STARTINGZONE)

### ISSUE THREAD

**Issue by Darkkob** [SallyWhitemane/Herod#437]
**Description:**
Quest Requires you to kill 6 Frenzied Stalkers but they arent spawning correctly (too slow), causing only 1 to spawn and aggro all the Northgate Rebels and immediatley die.

The Quest can be completed by Killing the Frenzied Stalkers by the Entrance.

**How it should work:**
All Northgate Rebels should be occupied fighting the Frenzied Stalkers and not immediatley killing them, the Player should be the only one able to kill them, so the quest can be properly completed.

**Wowhead links:**
https://www.wowhead.com/quest=14222/last-stand

![294951-last-stand](https://user-images.githubusercontent.com/83185943/116009738-8b84dc00-a61b-11eb-8a28-e1a77ea50ce8.jpg)

![WoWScrnShot_042521_230127](https://user-images.githubusercontent.com/83185943/116009673-524c6c00-a61b-11eb-8cc4-04f555294e23.jpg)

**Comment by HerodDev** [comment]
already fixed in rev 4, wait for server update
