### ISSUE TITLE
[NPC] King Llane (apparently) - Untargettable in Terokkar Forrest 

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#438]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The NPC model of what appears to be the King Llane NPC from the Karazhan Chess Event is currently untargettable in Veil Lithic, in Terokkar Forrest.
![lla0425](https://user-images.githubusercontent.com/82483575/116017799-35f20480-a606-11eb-93de-01a4a2b02720.png)

**How to reproduce:**
Navigate to Veil Lithic in Terokkar Forrest, located at roughly 25.4 70.8

**How it should work:**
This NPC should not be here.

**Wowhead links:**
https://www.wowhead.com/npc=21684/king-llane

**Comment by Ahumaya** [comment]
I turned around and found more
![lla20425](https://user-images.githubusercontent.com/82483575/116017865-59b54a80-a606-11eb-9d6f-31572c1e6c7c.png)

**Comment by HerodDev** [comment]
fixed in rev 7
