### ISSUE TITLE
[Quest] Sealing the Dream        (quest item doesn't work)

### ISSUE THREAD

**Issue by Kevingox4** [SallyWhitemane/Herod#445]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
when I use the quest item to finish the quest nothing happens

**How to reproduce:**
Take the quest and try using the item

**How it should work:**
Using the quest item should seal a portal

**Wowhead links:**
https://www.wowhead.com/quest=25250/sealing-the-dream

**Comment by HerodDev1** [comment]
Fixed in rev 27.
