### ISSUE TITLE
the character unstuck option

### ISSUE THREAD

**Issue by Kevingox4** [SallyWhitemane/Herod#446]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**

It returned me to my starting area since I am a Worgen it returned me to Gilneas
**How to reproduce:**
just use it

**How it should work:**
it says that I will die and spawn as a ghost next to a spirit healer in the nearest graveyard

**Wowhead links:**

**Comment by HerodDev5** [comment]
Fixed in rev 32
