### ISSUE TITLE
[QUEST] Triage - Credit Automatically Awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#447]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest credit for Triage is automatically awarded when the quest is accepted.

https://user-images.githubusercontent.com/82483575/116137878-bf9ee200-a699-11eb-9205-400b4b3e1d3f.mp4

**How to reproduce:**
Accept the quest Triage from Doctor Gustaf VanHowzen. Observe that quest credit is automatically awarded.

**How it should work:**
You should have to save 15 individual patients to earn quest credit.

**Wowhead links:**
https://www.wowhead.com/quest=6624/triage

**Comment by HerodDev1** [comment]
Fixed in rev 22.
