### ISSUE TITLE
[QUEST] I Was A Lot Of Things... - Domesticated Felboar has very long respawn time

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#452]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest I Was A Lot Of Things..., you use the Oronok's Boar Whistle to make boars dig up nearby tubers. Currently, this is working as intended, however once complete, the boar despawns, and the length of time between respawns (on an admittedly very empty server) is several minutes, adding a lot of time to complete this simple quest.

**How to reproduce:**
During the quest I Was A Lot Of Things..., use Oronok's Boar Whistle near a Shadowmoon Tuber Mound. Observe that a nearby boar will approach the mound and then an interactable Shadowmoon Tuber will spawn, and the Domesticated Felboar will despawn. Observe that the respawn timer is several minutes.

**How it should work:**
According to anecdotal evidence on the wowhead page for the Domesticated Felboar, the NPC has a reasonably short respawn timer, judging by old comments regarding skinning.

**Wowhead links:**
https://www.wowhead.com/quest=10514/i-was-a-lot-of-things
https://www.wowhead.com/npc=21195/domesticated-felboar

**Comment by HerodDev5** [comment]
Fixed in rev 38.
