### ISSUE TITLE
[NPC] Coilskar Defender - Untargettable, doesn't attack

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#453]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The specific Coilskar Defender at roughly 47.2 27.6 in Shadowmoon Valley is untargettable and doesn't attack the player. Please see screenshot below:
![coi0427](https://user-images.githubusercontent.com/82483575/116332443-61582900-a797-11eb-9a8e-5e558d890e23.png)

**How to reproduce:**
Navigate to roughly 47.2 27.6 in Shadowmoon Valley, and observe the Coilskar Defender model which can not be interacted with.

**How it should work:**
The NPC should behave like a normal hostile enemy.

**Wowhead links:**
https://www.wowhead.com/npc=19762/coilskar-defender

**Comment by HerodDev5** [comment]
Fixed in rev 38.
