### ISSUE TITLE
[QUEST] Feeding the Hungry and the Hopeless - NPCs say text from different quest

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#455]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Feeding the Hungry and the Hopeless, when you use the Westfall Stew item, some nearby Homeless Stormwind Citizen NPCs will give "clue" responses to the earlier quest Murder Was The Case That They Gave Me.
![fth0428](https://user-images.githubusercontent.com/82483575/116470137-9ff1f000-a838-11eb-805c-ba52dd56b0e1.png)

**How to reproduce:**
During the quest Feeding the Hungry and the Hopeless, approach Homeless Stormwind Citizen NPCs and use the Westfall Stew item. On occassion (about 8 of the 20 NPCs I fed), they will give "clue" responses.

**How it should work:**
These NPCs should not provide "clue" responses.

**Wowhead links:**
https://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless
https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me

**Comment by HerodDev1** [comment]
Fixed in rev 27.
