### ISSUE TITLE
[NPC] Brubaker - Should appear dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#457]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The NPC Brubaker in Redridge Mountains currently appears to be alive, when he should appear to be dead.
![bru0428](https://user-images.githubusercontent.com/82483575/116483617-06810900-a84d-11eb-814a-689915fecbdb.png)

**How to reproduce:**
Navigate to Brubaker in Redridge Mountains, located at roughly 53.0 67.6. Observe that he appears to be alive.

**How it should work:**
Brubaker should be dead.

**Wowhead links:**
https://www.wowhead.com/npc=43508/brubaker

**Comment by HerodDev** [comment]
fixed rev 8
