### ISSUE TITLE
[QUEST] Bird is the Word - Text issue in quest text

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#460]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest text for Bird is the Word is pretty messed up, please see screenshot below:
![bit0428](https://user-images.githubusercontent.com/82483575/116499742-7d7cc880-a872-11eb-9d0b-eef8a615f6bf.png)

**How to reproduce:**
Accept the quest Bird is the Word from Bingles Blastenheimer. Observe the issues in the quest text.

**How it should work:**
The quest text should read as it does in the wowhead page.

**Wowhead links:**
https://www.wowhead.com/quest=27032/bird-is-the-word

**Comment by HerodDev1** [comment]
Fixed in rev 27.
