### ISSUE TITLE
[Quest]Miner's Fortune

### ISSUE THREAD

**Issue by TheRealTangsten** [SallyWhitemane/Herod#463]
**Description:** Brak Blusterpipe doesn't have the gossip menu for turning in the quest.

**How to reproduce:** Accept the quest from Ratchet, obtain the Cats Eye Emerald, go to Brack Blusterpipe in Nozzlepot's Outpost.

**How it should work:** You should be able to turn in the quest.

**Wowhead links:** https://www.wowhead.com/quest=29015/miners-fortune

photos:
https://i.imgur.com/mddtO7Z.jpg
https://i.imgur.com/7FxnOL4.jpg
https://i.imgur.com/gVG3wbV.jpg

**Comment by HerodDev1** [comment]
I do not see problem with this quest ;)

![image](https://user-images.githubusercontent.com/86661453/124666301-21f03c00-deae-11eb-98e7-f6fa121d6e10.png)
