### ISSUE TITLE
[QUEST] Twisted Twilight Ties - Hansel Heavyhands has no dialog options.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#469]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Twisted Twilight Ties, the player is instructed to speak with Hansel Heavyhands to help him. Currently, Hansel has no dialog options to assist him.
![ttt0429](https://user-images.githubusercontent.com/82483575/116648900-d9fbe880-a943-11eb-840c-44a996ef00c7.png)

**How to reproduce:**
Accept the quest Twisted Twilight Ties. Speak with Hansel Heavyhands next to the quest giver. Observe that no dialog options are present.

**How it should work:**
Hansel Heavyhands should have a dialog option available to help complete the quest.

**Wowhead links:**
https://www.wowhead.com/quest=28060/twisted-twilight-ties

**Comment by HerodDev1** [comment]
Fixed in rev 27.
