### ISSUE TITLE
"Murder Was The Case That They Gave Me" Westfall Quest

### ISSUE THREAD

**Issue by WarlordXecc** [SallyWhitemane/Herod#472]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://youtu.be/BtUXvVaJGmQ
After you talk or bribe one of these mobs they're supposed to answer you and then be unable to speak to them again.
Here you can spam it over and over as seen in the video. Even when they're hostile and attacking you. Sometimes they don't even answer too.

**Comment by WarlordXecc** [comment]
Additionally, mobs on this quest have some cosmetic issues.
A few of them walk around and then instantly triggers sleep animation when standing still, looks pretty scuffed.

**Comment by WarlordXecc** [comment]
https://cata-twinhead.twinstar.cz/?quest=26209
https://cata-twinhead.twinstar.cz/?npc=42384
https://cata-twinhead.twinstar.cz/?npc=42386

You shouldn't tell people to use Wowhead. A lot of things has been changed since Cata in Shadowlands, even in the Cata world. Some NPCs are not where they used to be, some quests are changed or gone. Better to use a Cata Database if you want valid information.

**Comment by alexspew** [comment]
> https://cata-twinhead.twinstar.cz/?quest=26209
> https://cata-twinhead.twinstar.cz/?npc=42384
> https://cata-twinhead.twinstar.cz/?npc=42386
> 
> You shouldn't tell people to use Wowhead. A lot of things has been changed since Cata in Shadowlands, even in the Cata world. Some NPCs are not where they used to be, some quests are changed or gone. Better to use a Cata Database if you want valid information.

Not really, the classic quests are the same as they were from Cata. 1-60 (original content) were revamped from Cata, and never touched since.

**Comment by WarlordXecc** [comment]
> > https://cata-twinhead.twinstar.cz/?quest=26209
> > https://cata-twinhead.twinstar.cz/?npc=42384
> > https://cata-twinhead.twinstar.cz/?npc=42386
> > You shouldn't tell people to use Wowhead. A lot of things has been changed since Cata in Shadowlands, even in the Cata world. Some NPCs are not where they used to be, some quests are changed or gone. Better to use a Cata Database if you want valid information.
> 
> Not really, the classic quests are the same as they were from Cata. 1-60 (original content) were revamped from Cata, and never touched since.

Yes really, I've ran into a few things which did no longer match in Cata on Wowhead while testing stuff on Deus. Not a lot but things do exist and that's in the 1-60 world.

**Comment by HerodDev** [comment]
Well then use some other database like yours, i dont care which one, just provide info.

**Comment by HerodDev1** [comment]
Fixed in rev 20.
