### ISSUE TITLE
"Livin the Life" Westfall Quest Visual Bug

### ISSUE THREAD

**Issue by WarlordXecc** [SallyWhitemane/Herod#473]
![WoWScrnShot_043021_121317](https://user-images.githubusercontent.com/66841484/116681742-a81f6c00-a9ad-11eb-8179-6f736dec993a.jpg)

**Description:**
Visual bug, character is seen outside the box.

**How it should work:**
Should only see the box.

**Comment by HerodDev** [comment]
add wowhead links

**Comment by WarlordXecc** [comment]
https://cata-twinhead.twinstar.cz/?quest=26228

You shouldn't tell people to use Wowhead. A lot of things has been changed since Cata in Shadowlands, even in the Cata world. Some NPCs are not where they used to be, some quests are changed or gone. Better to use a Cata Database if you want valid information.

**Comment by HerodDev1** [comment]
Fixed in rev 20.
