### ISSUE TITLE
More Westfall Visual Bugs

### ISSUE THREAD

**Issue by WarlordXecc** [SallyWhitemane/Herod#476]
![WoWScrnShot_043021_125515](https://user-images.githubusercontent.com/66841484/116704847-28ed6080-a9cc-11eb-896b-5dffeb5cae1b.jpg)
![WoWScrnShot_043021_125813](https://user-images.githubusercontent.com/66841484/116704852-2a1e8d80-a9cc-11eb-806d-776764290135.jpg)
![WoWScrnShot_043021_153600](https://user-images.githubusercontent.com/66841484/116704857-2c80e780-a9cc-11eb-96ef-4069167944dd.jpg)

**Description:**
During the quest "Rise of the Brotherhood", Admiral Ripsnarl has no walking animation. He just stands still while gliding away on the ground.
After that event is finished, the worgen form of Ripsnarl is just standing in middle of the road with his animation for the cuffs.
Then when you get back to Westfall after turning in the quest in Stormwind, all the mobs and guards are just standing there watching each other but they should be fighting just like the guards did vs the Gnolls in the previous phase.

**Comment by HerodDev** [comment]
add wowhead links to quest/nps

**Comment by WarlordXecc** [comment]
https://cata-twinhead.twinstar.cz/?quest=26322
https://cata-twinhead.twinstar.cz/?npc=42778
https://cata-twinhead.twinstar.cz/?npc=42635
https://cata-twinhead.twinstar.cz/?npc=42748
https://cata-twinhead.twinstar.cz/?npc=594

**Comment by HerodDev1** [comment]
Fixed in rev 20.
