### ISSUE TITLE
[NPC] Joseph the Awakened - Multiple copies exist in Scarlet Monastery instances

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#477]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There are 2 Joseph the NPCs in two Scarlet Monastery instances, Graveyard and Library. Each offers different quests, for Graveyard and Library. Additionally, some of the Joseph the Awakened and Joseph the Crazed NPCs will be female on load sometimes. Please see screenshots below:
![jta0430](https://user-images.githubusercontent.com/82483575/116757598-ff383780-a9d3-11eb-83f4-1e7045bf4ce2.png)
![jta20430](https://user-images.githubusercontent.com/82483575/116757606-02332800-a9d4-11eb-832f-bcd20d49123d.png)
![jta30430](https://user-images.githubusercontent.com/82483575/116757608-04958200-a9d4-11eb-950b-0d737414d1c8.png)

**How to reproduce:**
Enter each of the Scarlet Monastery instances and observe the number, gender, and quests given by the Joseph the Awakened NPC. The Joseph the Crazed NPC in Cathedral does not seem to be affected. Must be on Alliance to see Joseph the Awakened. Horde characters will have Lillian Voss, who I have not confirmed if there is an issue with.

**How it should work:**
There should only be one Joseph the (something) NPC per instance, and all models should be male.

**Wowhead links:**
https://www.wowhead.com/npc=44728/joseph-the-awakened
https://www.wowhead.com/npc=44738/joseph-the-awakened
https://www.wowhead.com/npc=44741/joseph-the-crazed
https://www.wowhead.com/npc=44746/joseph-the-insane

**Comment by HerodDev5** [comment]
Fixed in rev 29
