### ISSUE TITLE
[QUEST] Without Rhyme or Reason - Mentions wrong NPC

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#478]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest text for Without Rhyme or Reason mentions Velonara for Alliance players instead of Joseph the Crazed.
![wrr0430](https://user-images.githubusercontent.com/82483575/116758859-a322e280-a9d6-11eb-9f92-4f9e819ddbec.png)

**How to reproduce:**
As an Alliance player, accept the quest Without Rhyme or Reason. Observe the quest text.

**How it should work:**
The quest text should reference Joseph the Crazed.

**Wowhead links:**
https://www.wowhead.com/quest=26994/without-rhyme-or-reason

**Comment by HerodDev1** [comment]
Fixed in rev 20.
