### ISSUE TITLE
[SPELL] Swift Flight Form - Most flight momentum is lost when leaving form.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#480]
**Description:**
When moving forward while in Swift Flight Form, exiting Swift Flight Form reduces your forward air speed to roughly a walking speed. This does not occur when using flying mounts, and does not occur on the Whitemane Mograine server. 

https://user-images.githubusercontent.com/82483575/116795688-7a652080-aa9c-11eb-8309-1dd68f0244f4.mp4

https://user-images.githubusercontent.com/82483575/116795693-7d601100-aa9c-11eb-92fd-45beb22bf20f.mp4

**How to reproduce:**
While in Swift Flight Form, fly forward at a constant speed (auto-run). While moving, de-activate Swift Flight Form, and observe that your character immediately slows down, as shown in the above video.

**How it should work:**
Flight momentum should be kept, corresponding to the direction of travel at the time the form is removed, as it works on the Mograine server and on Herod server with normal flying mounts.

**Database links:**
https://www.wowhead.com/spell=40120/travel-form

**Comment by HerodDev5** [comment]
Fixed in rev 26
