### ISSUE TITLE
[NPC] Teronis' Corpse - Should appear to be dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#483]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, the Teronis' Corpse NPC appears to be alive. Please also note that the nearby flower models should also be much smaller.
![ter0502](https://user-images.githubusercontent.com/82483575/116824775-8c54cb00-ab51-11eb-96bb-af24ada43798.png)

**How to reproduce:**
Navigate to Teronis' Corpse at roughly 20.2 38.8 in Ashenvale. Observe that the NPC appears to be alive

**How it should work:**
The NPC should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=3891/teronis-corpse

**Comment by HerodDev** [comment]
fixed rev 7
