### ISSUE TITLE
[QUEST] True Power of the Rod - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#486]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest credit for True Power of the Rod is automatically awarded when accepting the quest.

**How to reproduce:**
Accept the quest True Power of the Rod from Krolg in Ashenvale

**How it should work:**
Credit should not be automatically awarded, and the player should have to complete the quest normally.

**Database links:**
https://www.wowhead.com/quest=26482/true-power-of-the-rod

**Comment by HerodDev1** [comment]
Fixed in rev 20.
