### ISSUE TITLE
[QUEST] The Only Way Down is in a Body Bag - NPC Draw Distance too low

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#487]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The NPC Draw Distance is too low to easily complete this quest. The NPCs are off in the distance, but too far to be seen without flying out to see them. You can not see them from the Sniper Rifle seat. There are some closer spawns which can be seen, but most are too far away to see.

https://user-images.githubusercontent.com/82483575/116831805-385cdd00-ab77-11eb-9695-477f4f1f31d5.mp4

**How to reproduce:**
Attempt to complete the quest The Only Way Down is in a Body Bag. Please see my graphics settings below.
![image](https://user-images.githubusercontent.com/82483575/116831816-46aaf900-ab77-11eb-95ae-ed333e4188cc.png)

**How it should work:**
You should be able to see NPCs within the firing arc of the Sniper Rifle.

**Database links:**
https://www.wowhead.com/quest=25614/the-only-way-down-is-in-a-body-bag

**Comment by HerodDev1** [comment]
Fixed in rev 25.
