### ISSUE TITLE
[QUEST] Scavenged - Lack of world items

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Scavenged, the player needs to gather Northwatch Supply Crates. Currently, there are only 4 available items, which each have a very long respawn time. According to notes on the wowhead link, there should be more spawns deeper in the raptor den.

**How to reproduce:**
During the quest Scavenged, head into the raptor den at roughly 61.3 44.1 in Southern Barrens. Observe that there are very few spawns of the Northwatch Supply Crates.

**How it should work:**
There should be more crates within the raptor den, or the respawn timer should be lower.

**Database links:**
https://www.wowhead.com/quest=25002/scavenged
https://www.wowhead.com/object=202405/northwatch-supply-crate

**Comment by HerodDev1** [comment]
Fixed in rev 25.
