### ISSUE TITLE
[QUEST] Diplomacy By Another Means - Sabersnout is friendly and can't be killed.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#490]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sabersnout spawns as friendly, and can't be killed for quest credit. This prevents the quest from being completed.

**How to reproduce:**
During the quest Diplomacy By Another Means, use the item Horn of Challenge to summon Sabersnout in the quillboar arena. Observe that he is friendly.

**How it should work:**
Sabersnout should be hostile to the player.

**Database links:**
https://www.wowhead.com/quest=25044/diplomacy-by-another-means
https://www.wowhead.com/npc=37513/sabersnout

**Comment by HerodDev1** [comment]
Fixed in rev 25.
