### ISSUE TITLE
[QUEST] Hands Off Me Dig! - Lack of world items

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#491]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Hands Off Me Dig!, the player needs to gather 5 Bael Modan Artifacts. Currently there are only 2 available at a time, with a long respawn time for each of them. This makes the quest take a very long time to complete.

**How to reproduce:**
Navigate to roughly 47.6 86.5 in Southern Barrens with the quest Hands Off Me Dig!. Observe that there are very few Bael Modan Artifacts.

**How it should work:**
There should be many more Bael Modan Artifacts. The wowhead link identifies at least 7 spawns, possibly more.

**Database links:**
https://www.wowhead.com/object=202533/bael-modan-artifact
https://www.wowhead.com/quest=25106/hands-off-me-dig

**Comment by HerodDev1** [comment]
Fixed in rev 25.
