### ISSUE TITLE
[QUEST] Marley's Final Flight - Marley Twinbraid has no dialog option

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#492]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Marley's Final Flight, the player needs to interact with Marley Twinbraid to complete the quest. Currently, Marley has no dialog option, and the quest can not be completed.

![mff0503](https://user-images.githubusercontent.com/82483575/116908532-a56c8300-ac08-11eb-97d2-9507b610e747.png)

**How to reproduce:**
Accept the quest Marley's Final Flight. Speak with Marley Twinbraid. Observe that he does not have a dialog option.

**How it should work:**
Marley Twinbraid should have a dialog option to fly with him to complete the quest.

**Database links:**
https://www.wowhead.com/quest=25120/marleys-final-flight
https://www.wowhead.com/npc=39155/marley-twinbraid

**Comment by HerodDev1** [comment]
Fixed in rev 25.
