### ISSUE TITLE
[Quest] [Felwood] Break the Unbreakable

### ISSUE THREAD

**Issue by IamNylea** [SallyWhitemane/Herod#493]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Using quest item Claw of Tichondrius does not remove flames blocking the way to Xavathras.

**How to reproduce:**
Take quest Break the Unbreakable from Arcanist Delaris and go to Ruins of Constellas. Find the flaming barrier and use Claw of Tichondrius.

**How it should work:**
Claw of Tichondrius should remove flaming barrier.

**Database links:**
https://www.wowhead.com/quest=28113/break-the-unbreakable
https://www.wowhead.com/item=63031/claw-of-tichondrius

**Comment by HerodDev1** [comment]
Actually, it works on rev 23. I have lowered respawn time of flaming barrier
