### ISSUE TITLE
[QUEST] Raze Direhorn Post! - North Tent is difficult to set ablaze

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#495]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The North Tent during the quest Raze Direhorn Post! is difficult to set ablaze, as it requires the player to stand in a very specific location, which I found after moving through many locations around and in the tent. The other 2 tents do not have a similar issue.

**How to reproduce:**
During the quest Raze Direhorn Post, use the Tabetha's Torch item near each of the 3 tents. Observe that the North tent requires very specific positioning within the tent to work, where the other 2 tents merely require you to be close enough.

**How it should work:**
The North tent should work the same as the other 2 tents.

**Database links:**
https://www.wowhead.com/quest=27429/raze-direhorn-post

**Comment by HerodDev1** [comment]
Fixed in rev 25.
