### ISSUE TITLE
[QUEST] Boulder Delivery - Event does not begin after quest completed.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#498]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After completing the quest Boulder Delivery, a small event should play out with Lilith the Lithe. Currently, the event does not play.

**How to reproduce:**
Complete the quest Boulder Delivery. Observe that no event triggers.

**How it should work:**
A small event showing Lilith the Lithe breaking a boulder should play out.

**Database links:**
https://www.wowhead.com/quest=28618/boulder-delivery

**Comment by HerodDev1** [comment]
Fixed in rev 23.
