### ISSUE TITLE
[QUEST] Tree Delivery - Event does not end after quest completed.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#500]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
A follow up quest to #498, after completing Tree Delivery, Kilram spawns a tree which he attacks with his axe. Unlike in #498 where the event did not start, the Tree event after Tree Delivery does not end. Please see the brief video below where the event starts, and note that as of submitting this ticket, the event is still ongoing.

https://user-images.githubusercontent.com/82483575/117177369-91ef2280-ad96-11eb-8c6e-a04b11cd71f9.mp4

https://cdn.discordapp.com/attachments/830854551736680518/839542254296104960/World_of_Warcraft_2021-05-05_11-39-41.mp4

**How to reproduce:**
Complete the quest Tree Delivery. Observe that Kilram does not end the event.

**How it should work:**
The event should end after a short time with Kilram successfully chopping the tree.

**Database links:**
https://www.wowhead.com/quest=28626/tree-delivery

**Comment by HerodDev1** [comment]
Fixed in rev 23.
