### ISSUE TITLE
[QUEST] Echo Three - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#501]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When accepting the quest Echo Three, quest credit is automatically awarded.

https://user-images.githubusercontent.com/82483575/117178231-720c2e80-ad97-11eb-83e1-ba345b3ce5e8.mp4

**How to reproduce:**
Accept the quest Echo Three from Umi Rumplesnicker. Observe that credit is instantly awarded.

**How it should work:**
The quest credit should only be awarded after completing the quest objectives.

**Database links:**
https://www.wowhead.com/quest=28630/echo-three

**Comment by Ahumaya** [comment]
Update to ticket, quest also allows you to turn the quest in to Umi Rumplesnicker, when you should only be able to turn it in to the Echo Three NPC.

**Comment by HerodDev1** [comment]
Checked twice, kill credit is awarded on retail also. However, you are right with Umi as quest ender. You should handle it only in "ECHO TREE" GO.

**Comment by HerodDev1** [comment]
Fixed in rev 23.
