### ISSUE TITLE
[NPC] Frostmaul Preserver - Can be skinned

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#502]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Frostmaul Preserver NPCs in Frostwhisper Gorge in Winterspring can be skinned.

**How to reproduce:**
Kill a Frostmaul Preserver with Skinning as a skill. Observe that the dead NPC can be skinned.

**How it should work:**
Frostmaul Preservers should only be able to be mined.

**Database links:**
https://www.wowhead.com/npc=7429/frostmaul-preserver

**Comment by HerodDev5** [comment]
Fixed in rev 37
