### ISSUE TITLE
[NPC] Galaen's Corpse - Appears to be alive

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#504]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Galaen's Corpse NPC in Bloodmyst Isle appears to be alive. He should appear to be dead.
![gal0506](https://user-images.githubusercontent.com/82483575/117244527-d0202c80-adfe-11eb-9a79-05c9caf094df.png)

**How to reproduce:**
Navigate to roughly 37.6 61.2 in Bloodmyst Isle. Observe that Galen's Corpse appears to be alive.

**How it should work:**
Galaen's Corpse should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=17508/galaens-corpse

**Comment by HerodDev5** [comment]
Fixed in rev 37
