### ISSUE TITLE
[QUEST] Ending Their World - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#505]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest credit for Ending Their World is automatically awarded when accepting the quest.

https://user-images.githubusercontent.com/82483575/117245669-d1525900-ae00-11eb-810e-ce1c6927e2f0.mp4

**How to reproduce:**
Accept the quest Ending Their World from Demolitionist Legoso in Bloodmyst Isle.

**How it should work:**
The credit should only be awarded after completing the escort quest.

**Database links:**
https://www.wowhead.com/quest=9759/ending-their-world#

**Comment by SallyWhitemane** [comment]
Fixed in rev 13.
