### ISSUE TITLE
[ITEM] Infernal Power Core - Drops for Alliance Players

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#509]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Infernal Power Core item is dropping for Alliance players. This item starts a Horde only quest and should only drop for Horde players.

**How to reproduce:**
Kill Lesser Infernals in southern Desolace as an Alliance player. If Infernal Power Core drops, attempt to use it, and observe that you can not accept the quest as Alliance.

**How it should work:**
The Infernal Power Core item should not drop for Alliance players.

**Database links:**
https://www.wowhead.com/item=49200/infernal-power-core

**Comment by SallyWhitemane** [comment]
Fixed in rev 11.
