### ISSUE TITLE
[QUEST] No One Here Gets Out Alive - Cinematic Crash

### ISSUE THREAD

**Issue by DarokWazo** [SallyWhitemane/Herod#511]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
"No One Here Gets Out Alive" quest in Hillsbrad Foothills during the "Welcome to the Machine" questline
Cinematic starts, crashes game about the end, and then ports you back when game restarts. Makes you full up high if you cancel out cinematic

**How to reproduce:**
Accept quest and let cinematic play

**How it should work:**
Cinematic should end, and you should be alive and well (and so should be your game)

**Database links:**
![screen 1](https://user-images.githubusercontent.com/83889609/117556304-a0c02880-b067-11eb-8a21-a75c9f546141.png)
![screen 2](https://user-images.githubusercontent.com/83889609/117556307-a1f15580-b067-11eb-99ce-c589d4d6ff52.png)
![screen 3](https://user-images.githubusercontent.com/83889609/117556308-a289ec00-b067-11eb-8267-259721f3c70d.png)

**Comment by HerodDev** [comment]
Always remember to add wowhead links
https://www.wowhead.com/quest=28192/no-one-here-gets-out-alive

**Comment by SallyWhitemane** [comment]
I cannot reproduce that its either your client problem or server crash related to #555 as second ss indicates server crash, not game crash.
