### ISSUE TITLE
[NPC] Underbog Lord - Uses wrong model

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#513]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Underbog Lord NPCs in The Underbog are using a mountain giant model, and not the bog lord model.
![ubl0509](https://user-images.githubusercontent.com/82483575/117582399-77cf8000-b0c7-11eb-9f25-3f71eefa17f8.png)

**How to reproduce:**
Enter The Underbog. Observe the Underbog Lord NPCs.

**How it should work:**
The Underbog Lord NPCs should be using a bog lord model.

**Database links:**
https://www.wowhead.com/npc=17734/underbog-lord

**Comment by HerodDev5** [comment]
Fixed in rev 37
