### ISSUE TITLE
[Quest] The Last Refugee

### ISSUE THREAD

**Issue by Xenothang** [SallyWhitemane/Herod#516]
https://www.wowhead.com/quest=13605/the-last-refugee

**Description:**
NPC doesn't attack any more or pulls any of them.

**How to reproduce:**
Accept the Quest and watch the NPC just speedrunning hope

**How it should work:**
Should attack mobs and trigger combat too

https://youtu.be/kZi7hAkSRYQ?t=142

**Comment by SallyWhitemane** [comment]
Fixed in rev 11.
