### ISSUE TITLE
[Quest] Mutual Aid 

### ISSUE THREAD

**Issue by Xenothang** [SallyWhitemane/Herod#517]
**Description:**
Questitem is multiply usable on dead mobs
Mobs also don't dash forward when using they fire spell

**How to reproduce:**
Use Quest item on corpse multiply times.
To see the spell just trigger combat

**How it should work:**
Only one per Mob
Mobs should Dash while using the Rush of Flame

**Database links:**
https://www.wowhead.com/quest=13576/mutual-aid

for the Spell
https://youtu.be/4peR1fLNAZo?t=91

**Comment by SallyWhitemane** [comment]
Fixed in rev 9.
