### ISSUE TITLE
mob lvls

### ISSUE THREAD

**Issue by clark1978** [SallyWhitemane/Herod#52]
**Description:**
Mob levels in Ellwyn not correct. Some mobs as low as level 2.

**Comment by HerodDev** [comment]
Not enough information, provide some proofs for which mobs have bad level.

**Comment by clark1978** [comment]
For example kobolds in and around fargodeep mine supposed to level 5-7 they are actully 2-7 on beta. jasperload mine is the same mob levels are 2-8 supposed to be 6-8. Several wolf and bears are level 2 should be 5+
