### ISSUE TITLE
Bug that takes part in all quests

### ISSUE THREAD

**Issue by MrFolls** [SallyWhitemane/Herod#53]
**Description:**I got into a party than suddenly all quest kill rates/drop rates were rly lowered what do i mean if before all mobs were dropping quest items kill rates now it was like once per 3,4 i did convert to raid later just to see how a raid grop looks like than all quest were impossible to be done. Since later into the game i think there should be some Raid quests and etc. even if i was doing normal world quest they still should have been able to be done I did 2 quest report bugs bcs there was literally no drop rates i found that it was because of the raid thinky that im reproting right now.
**How to reproduce:**

**How it should work:**

**Comment by HerodDev** [comment]
When you are in raid mode you can't do normal quests, only those that are marked as Raid, that mechanic exist from the begining of WoW.
