### ISSUE TITLE
[OBJECT] Really Strong Ogre Coffee Keg - Does not sober up the player. Makes the player more drunk.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#530]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Really Strong Ogre Coffee Keg, spawned after completing Into the Soulgrinder, should sober up the player after drinking from the Blade's Edge Ogre Brew Keg. Currently, the Coffee Keg makes the player instantly smashed, and does not sober up the player.

https://user-images.githubusercontent.com/82483575/117898583-e3157f80-b28a-11eb-8a97-b816d3f05f8f.mp4

**How to reproduce:**
Complete the quest Into the Soulgrinder. Attempt to drink from the Really Strong Ogre Coffee Keg. Observe that the player character becomes instantly drunk.

**How it should work:**
The Really Strong Ogre Coffee Keg should lessen the effects of alcohol, making the player less drunk on each use.

**Database links:**
https://www.wowhead.com/object=185914/really-strong-ogre-coffee-keg

**Comment by HerodDev5** [comment]
Fix in rev 26
