### ISSUE TITLE
[OBJECT] Obsidia's Egg - Interaction does not work

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#532]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When interacting with Obsidia's Egg in the Blade's Edge Mountains, no text box pops up. This prevents the player from summoning Obsidia.

**How to reproduce:**
Attempt to interact with Obsidia's Egg in the Blade's Edge Mountains.

**How it should work:**
On interaction, a text box should pop up. If you have 35 or more Apexis Shards, it should have a dialog option to summon Obsidia.

**Database links:**
https://www.wowhead.com/object=185932/obsidias-egg

**Comment by HerodDev5** [comment]
Fixed in rev 38.
