### ISSUE TITLE
[QUEST] Measuring Warp Energies - Quest locations are not large enough

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#534]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Measuring Warp Energies, the player needs to approach the 4 Pipelines outside of Manaforge B'naar. Currently, the active areas where the player can use the item Warp-Attuned Orb are very limited, requiring the player to be in a very specific location around each of the 4 pipelines.

https://user-images.githubusercontent.com/82483575/118051094-081af880-b346-11eb-829d-e6dc5812a43d.mp4

**How to reproduce:**
With the quest Measuring Warp Energies, approach each of the pipelines. Walk around the base of each pipeline where it intercepts the ground. Attempt to use the Warp-Attuned Orb. Observe that while the orb does work in one location for each pipeline, the rest of the pipe does not work, and there is no indication to the player as to where they need to stand.

**How it should work:**
The full base of the pipeline as it intercepts the ground should qualify for the Warp-Attuned Orb.

**Database links:**
https://www.wowhead.com/quest=10313/measuring-warp-energies

**Comment by HerodDev5** [comment]
Fixed in rev 37
