### ISSUE TITLE
[NPC] Withered Corpse - Stands and breathes, but is marked as dead.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#537]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, Withered Corpses appear to be alive, but are marked as dead.
![wit0512](https://user-images.githubusercontent.com/82483575/118075082-ee44da00-b374-11eb-84ec-d416b39a8c23.png)

**How to reproduce:**
Navigate to roughly 61.2 44.0 in Netherstorm. Observe the Withered Corpses.

**How it should work:**
The corpses should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=20561/withered-corpse

**Comment by HerodDev5** [comment]
Fixed in rev 37
