### ISSUE TITLE
[QUEST] Keeping the Enemy at Bay - Flaming Oil does not ignite sails

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#538]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the daily quest Keeping the Enemy at Bay, the player must use the Flaming Oil item to ignite the sails of the 3 ships in the bay. Currently, using the item on the sails does not give quest credit.

**How to reproduce:**
Accept the quest Keeping the Enemy at Bay. Speak with Ayren Cloudbreaker and choose the dialog option "I need to intercept the Dawnblade reinforcements." While in flight, attempt to use the Flaming Oil item provided by the quest on the sails of the ships. Observe that no quest credit is awarded.

**How it should work:**
When using the Flaming Oil on the sails, the sails should ignite and quest credit should be given.

**Database links:**
https://www.wowhead.com/quest=11543/keeping-the-enemy-at-bay
https://www.wowhead.com/item=34489/flaming-oil

**Comment by HerodDev5** [comment]
Fixed in rev 38.
