### ISSUE TITLE
Verog the dervish

### ISSUE THREAD

**Issue by Pallaladin** [SallyWhitemane/Herod#54]
**Description:**

Verog is a monster to kill for a quest he should appear after you kill Wyneth, but in the previous extention he appeared after you kill a number of kolkar near where he normally spawn and he still appear after a monster died and call for him and he should not.

**How to reproduce:**

Kill some kolkar near the wailing cavern he should spawn

**How it should work:**

he shouldn't spawn when you kill normal kolkar only when you kill Wyneth

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=851/verog-the-dervish

**Comment by HerodDev** [comment]
fixed rev 10
