### ISSUE TITLE
[QUEST] The Battle Must Go On - Irespeakers award double credit

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#540]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest The Battle Must Go On, killing Irespeakers awards double credit for "Burning Legion Demon slain".

**How to reproduce:**
Accept the quest The Battle Must Go On. Kill Irespeakers. Observe quest credit count.

**How it should work:**
Irespeakers should only award 1 count of quest credit.

**Database links:**
https://www.wowhead.com/quest=11537/the-battle-must-go-on

**Comment by HerodDev5** [comment]
Fixed in rev 38.
