### ISSUE TITLE
[NPC] Deathshadow Spellbinder - Turns into a gnome when aggroed.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#545]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When aggroed, these NPCs turn into gnomes.

https://user-images.githubusercontent.com/82483575/118201115-5f8b9800-b41c-11eb-9b81-dd9d1cb70d36.mp4

**How to reproduce:**
Engage Deathshadow Spellbinders in combat

**How it should work:**
They should not turn into gnomes

**Database links:**
https://www.wowhead.com/npc=22342/deathshadow-spellbinder

**Comment by HerodDev5** [comment]
Fixed in rev 38.
