### ISSUE TITLE
[OBJECT] Land Mine - Missing spawns, does nothing

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#549]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Land Mine objects in Azshara, located around 28.2 54.0, are very limited in number of spawns. The small valley should be almost completely filled with them. Additionally, they currently just despawn when walked over, and do not explode.

https://user-images.githubusercontent.com/82483575/118384293-92738e80-b5ca-11eb-8529-b6000113eca1.mp4

**How to reproduce:**
Navigate to 28.2 54.0 in Azshara. Observe the limited number of Land Mine objects, and that they do nothing when walked on.

**How it should work:**
There should be more spawns, and they should explode and knock back the player when tread upon.

**Database links:**
https://www.wowhead.com/object=202472/land-mine

**Comment by SallyWhitemane** [comment]
@Ahumaya I cannot reproduce that, there are many spawns of them in that area (140 to be exact), also explosion correctly cause jump back. Maybe jump part is related to #570, please check that after update.

**Comment by HerodDev** [comment]
fixed rev 10
