### ISSUE TITLE
[NPC] Lieutenant Sanders - Should appear to be dead (and hung)

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#551]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, Lieutenant Sanders appears to be alive.
![lie0516](https://user-images.githubusercontent.com/82483575/118411686-68b67800-b65b-11eb-84ab-105287a64df3.png)

**How to reproduce:**
Navigate to Lieutenant Sanders in Tirisfal. Observe that he appears to be alive.

**How it should work:**
Sanders should be hanging upside down from the tree and should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=13158/lieutenant-sanders

**Comment by SallyWhitemane** [comment]
Fixed in rev 13.
