### ISSUE TITLE
[NPC] Forward Commander Onslaught - Appears in wrong location at wrong level

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#552]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
A copy of Forward Commander Onslaught, and 5 Worgen Rusher NPCs appear in Forsaken Forward Command. There NPCs should not be here.

**How to reproduce:**
Complete the quest To Forsaken Forward Command. Observe the 5 level 1 Elite Worgen Rusher NPCs surrounding a level 1 Elite Forward Commander Onslaught NPC.

**How it should work:**
These 6 NPCs should not be here. No idea where they should be, though.

**Database links:**
https://www.wowhead.com/npc=45315/forward-commander-onslaught
https://www.wowhead.com/npc=45534/forward-commander-onslaught
https://www.wowhead.com/npc=45375/worgen-rusher
https://www.wowhead.com/npc=45535/worgen-rusher

**Comment by HerodDev5** [comment]
Fixed in rev 45.
