### ISSUE TITLE
[NPC] Forsaken Vanguard - Should appear to be dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#553]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Forsaken Vanguard NPCs in Dreadwatch Outpost, Ruins of Gilneas should appear to be dead.
![fsv0516](https://user-images.githubusercontent.com/82483575/118423166-05900a00-b68a-11eb-9f48-826aa80177fd.png)

**How to reproduce:**
Navigate to roughly 52.6 32.6 in Ruins of Gilneas. Observe that the Forsaken Vanguard at this location appear to be alive.

**How it should work:**
They should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=45280/forsaken-vanguard

**Comment by HerodDev5** [comment]
Fixed in rev 45.
