### ISSUE TITLE
neckBug losing stats

### ISSUE THREAD

**Issue by Veng666** [SallyWhitemane/Herod#554]
I've found out on my warrior tank that OS 10 man tank neck quest:
https://www.wowhead.com/item=44660/drakescale-collar#reward-from-q
gives me more stamina and armor than a better neck, boundless ambition
https://www.wowhead.com/item=40387/boundless-ambition

in fact with the second one I lose armor and stamina beside the fact that it gives me more stamina and armor!

I cancelled the cache 4 times at least and relogged; nothing change.
i provide you a screenshoot

**How to reproduce:**
take the 2 neck on a pg and see what happen to stats stamina/armor

**How it should work:**
i should have more armor and stam and not losing any of them!
i also dont' know why drakescale collar gives me 473 armor randomly beside the fact neck itself has no armor stat

**screenshot
![neck](https://user-images.githubusercontent.com/84307364/118445472-c516a780-b6ee-11eb-8dd1-b192643dae18.png)

**Comment by SallyWhitemane** [comment]
This is BT for cataclysm PTR realm, please make proper issue on wotlk one.
