### ISSUE TITLE
[QUEST] Rain of Destruction - Durak has no dialog options, respawn times very long

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#558]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Durak does not have an option to transform the player back into Imp form if the form is lost. Additionally, the respawn time of Raging Ancients needed for this quest is very long. On returning to Durak after waiting for respawn, the Imp form was removed prior to reaching him.

**How to reproduce:**
During the quest Rain of Destruction, kill Raging Ancients and wait for them to respawn. Observe the respawn time. Additionally, remove the Imp Disguise and attempt to speak with Durak to get another.

**How it should work:**
There should either be enough Raging Ancients to quickly kill 5 of them, or the respawn timer should be lowered, preferably both. Additionally, Durak should have an option to transform the player into an Imp again.

**Database links:**
https://www.wowhead.com/quest=13798/rain-of-destruction

**Comment by SallyWhitemane** [comment]
Any proof Durak should have gossip option?

**Comment by Ahumaya** [comment]
The quest text in game states to "Speak with Durak to reapply Imp Disguise.", but I am not able to find an immediate online reference showing this option.

**Comment by cloud1121** [comment]
"If you somehow lose your imp disguise, when you try to use the quest item, it will just keep telling you "requires Splintertree Tower". Speak to Durak inside the mine to reacquire imp disguise and try again." From Comments in link

**Comment by SallyWhitemane** [comment]
Fixed in rev 11.
