### ISSUE TITLE
[OBJECT] Ritual Gem - Duplicates at every spawn

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#559]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Each spawn of Ritual Gem in Satyrnaar in Ashenvale has two duplicate spawns.
![WoWScrnShot_051721_173535](https://user-images.githubusercontent.com/82483575/118564639-4cd3d480-b736-11eb-847b-ead9c24c7fc7.jpg)

**How to reproduce:**
Navigate to roughly 81.5 48.4 in Ashenvale. Observe the Ritual Gem spawns.

**How it should work:**
There should only be one gem, with portal vectors underneath it.

**Database links:**
https://www.wowhead.com/object=194464/ritual-gem

**Comment by SallyWhitemane** [comment]
Fixed in rev 9.
