### ISSUE TITLE
Paladin Consecrate placed on Ceiling

### ISSUE THREAD

**Issue by cloud1121** [SallyWhitemane/Herod#560]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In tight area's, placing consecrate will be placed on the ceiling instead of the floor. 

**How to reproduce:**
Fastest way to reproduce is in Stormwind Stockades. Any of the halls consecrate will appear on the ceiling. 

**How it should work:**
It should go below your feet on the floor.

**Database links:**

**Comment by HerodDev5** [comment]
Fixed in rev 29
