### ISSUE TITLE
[QUEST] Vorsha the Lasher - Event does not activate. Vorsha already up and does not give quest credit.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#561]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Vorsha the Lasher, the player must escort an NPC to an island, and then begin an event which ends with killing Vorsha the Lasher. Currently, Vorsha the Lasher spawns as a normal NPC, and does not provide quest credit when killed. Additionally, the event which would spawn Vorsha the Lasher normally does not function.

**How to reproduce:**
Attempt to complete Vorsha the Lasher as normal. Observe that when you reach the island, Vorsha the Lasher is already spawned, and killing it does not provide quest credit.

**How it should work:**
Vorsha the Lasher should spawn after a short event on the island.

**Database links:**
https://www.wowhead.com/quest=6641/vorsha-the-lasher

**Comment by HerodDev1** [comment]
Fixed in rev 23.
