### ISSUE TITLE
[QUEST] Put Out The Fire - Freezing Surger does not spawn

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#562]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Put Out The Fire, the Freezing Surger does not spawn. There is no dialog option with Arctanus to spawn in one.

**How to reproduce:**
Accept the quest Put Out The Fire. Observe that no Freezing Surger spawns.

**How it should work:**
A Freezing Surger should spawn when accepting the quest. If the Freezing Surger is lost, a dialog option should appear on Arctanus to spawn one.

**Database links:**
https://www.wowhead.com/quest=13884/put-out-the-fire

**Comment by SallyWhitemane** [comment]
Fixed in rev 9.
