### ISSUE TITLE
[WARLOCK] Self buffs disappear on logout

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#563]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On log out, Warlock self buffs, such as Demon Armor and Soul Link are removed from the player.

**How to reproduce:**
On a Warlock, cast Demon Armor. Log out, then log back in. Observe that Demon Armor is no longer applied.

**How it should work:**
Demon Armor, Soul Link, and other Warlock self buffs should persist through sessions.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=687
https://cata-twinhead.twinstar.cz/?spell=19028

**Comment by SallyWhitemane** [comment]
If I remember correctly pet related auras shouldn't get saved on logout, so I didn't Soul Link part. If Soul Link should get saved, please make separate issue with proof. Fixed in rev 9.
