### ISSUE TITLE
Mordei The Earthrender(Rare Spawn)

### ISSUE THREAD

**Issue by cloud1121** [SallyWhitemane/Herod#565]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mordei does not break his patrol when entering combat, and only attacks if you are in front of him. 

https://i.imgur.com/7sSlkmd.png

**Edit** Updated with correct Image Link

**How to reproduce:**
Fight Mordei.

**How it should work:**
He should stop patrolling to attack

https://youtu.be/TITw49x8DYs?t=268

**Database links:**
https://www.wowhead.com/npc=43488/mordei-the-earthrender#drops;50

**Comment by SallyWhitemane** [comment]
Fixed.
