### ISSUE TITLE
[Quest] To New Thalanaar 

### ISSUE THREAD

**Issue by cloud1121** [SallyWhitemane/Herod#567]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
To New Thalanaar quest in Feralas has an issue with distance to Taxi Stand. Impossible To board hippogryph

https://i.imgur.com/ykSfnMT.png

**How to reproduce:**
Start Quest, Talk to Flight master. 

**How it should work:**
Should auto put character on the hippogryph to fly to New Thalanaar. 

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=25481

**Comment by cloud1121** [comment]
Edit: Updated Database link with correct Quest

**Comment by SallyWhitemane** [comment]
Fixed.
