### ISSUE TITLE
[QUEST] Fuselight, Ho! - The Uncrashable can spawn an unlimited number of times if mounted

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#569]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, if the player is mounted and attempts to ride The Uncrashable during the quest Fuselight, Ho!, the player will receive an error stating that "You are mounted". However, a version of The Uncrashable will spawn without the player on it, which will travel south to Fuselight-by-the-Sea. This interaction has no limits, as shown in the videos below.

https://user-images.githubusercontent.com/82483575/119430194-f3d7e380-bcd5-11eb-82a1-047c59f5de96.mp4

https://user-images.githubusercontent.com/82483575/119430210-fa665b00-bcd5-11eb-97b5-d3b873476092.mp4

https://user-images.githubusercontent.com/82483575/119430226-018d6900-bcd6-11eb-929c-6d21a7a915d3.mp4

**How to reproduce:**
Accept the quest Fuselight, Ho!. While mounted, attempt to interact with The Uncrashable. Observe as a new copy spawns under the player, and then flies off.

**How it should work:**
The player should either be dismounted from their mount and forced into the The Uncrashable vehicle, or the duplicate The Uncrashable should not spawn.

**Database links:**
https://www.wowhead.com/quest=27762/fuselight-ho
https://www.wowhead.com/npc=48708/the-uncrashable

**Comment by HerodDev1** [comment]
Fixed in rev 23.
