### ISSUE TITLE
Arborcide - Reprogrammed Shredder Recharge not functioning

### ISSUE THREAD

**Issue by SylahUmehara** [SallyWhitemane/Herod#57]
**Description:**
Reprogrammed shedder recharge ability is not working, when casted shows up as "immune" with no healing effect

**How to reproduce:**
Enter a reprogrammed shredder with the quest, use ability.

**How it should work:**
Refer to link https://www.wowhead.com/spell=66937/recharge , should heal 70% on cast with 12sec cooldown

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=14155/arborcide

**Comment by SallyWhitemane** [comment]
Fixed.
