### ISSUE TITLE
[ALL CLASSES] Charge - Using charge pacifies player

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#570]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After using the Charge ability, the Warrior will not be able to auto-attack, and the charged enemy will not engage the player in combat. Additionally, the player is now in some strange status, and is treated as stunned, facing the wrong way, unable to move, but is able to move around.

https://user-images.githubusercontent.com/82483575/119552668-61c8ed00-bd60-11eb-8f80-d093d8e799e8.mp4

**How to reproduce:**
On a Warrior, Charge an Enemy, then start Auto-Attack and attempt to attack the target, or any enemy. Only a relog fixes.

**How it should work:**
Charge should not pacify the player.

**Database links:**
https://www.wowhead.com/spell=100/charge

**Comment by Ahumaya** [comment]
Druids also affected.

**Comment by SallyWhitemane** [comment]
Possibly fixed in rev 12. For 20 tries I reproduced it only once, let me know if it works after update.

**Comment by cloud1121** [comment]
I'll test after update goes live

**Comment by SallyWhitemane** [comment]
@cloud1121 @Ahumaya Can I safely assume issue has been resolved?

**Comment by cloud1121** [comment]
@SallyWhitemane just tested, working!!!
