### ISSUE TITLE
[QUEST] It's All Mine - Credit Automatically Awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Upon accepting the quest It's All Mine, credit is automatically awarded.

**How to reproduce:**
Accept the quest It's All Mine. Observe that credit is automatically awarded.

**How it should work:**
Credit should only be awarded after completing the goals of the quest.

**Database links:**
https://www.wowhead.com/quest=25677/its-all-mine

**Comment by SallyWhitemane** [comment]
Fixed in rev 13.
