### ISSUE TITLE
The Hunt For Sylvanas: Unable to complete worgen intro

### ISSUE THREAD

**Issue by cloud1121** [SallyWhitemane/Herod#574]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Find Sylvanas Quest(Final Worgen Quest) Tobias(Escort) gets stuck in door.

**How to reproduce:**
Start Quest "The Hunt For Sylvanas"

**How it should work:**
Escort should complete path to spawn sylvanas to trigger the phase to go to Stormwind. 

**Database links:**
https://www.wowhead.com/quest=24902/the-hunt-for-sylvanas

**Comment by HerodDev** [comment]
fixed rev 12
