### ISSUE TITLE
[QUEST] Timely Arrival - Escort does not start

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#575]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On accepting the quest Timely Arrival, the escort event does not start.

**How to reproduce:**
Accept the quest Timely Arrival. Observe as the escort event does not start.

**How it should work:**
The escort event should begin as normal.

**Database links:**
https://www.wowhead.com/quest=13510/timely-arrival

**Comment by HerodDev** [comment]
fixed rev 14
