### ISSUE TITLE
[NPC] Flesh Eater - Does not engage in combat

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#577]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Flesh Eaters at Raven Hill Cemetary in Darkshire do not engage in combat with the player or with player pets. They just stand there.

https://user-images.githubusercontent.com/82483575/120045178-fcc9fd00-bfd4-11eb-8b1d-31148f83d23c.mp4

**How to reproduce:**
Engage Flesh Eaters in combat. Observe that they do nothing.

**How it should work:**
They should engage in combat in a normal fashion.

**Database links:**
https://www.wowhead.com/npc=3/flesh-eater

**Comment by HerodDev5** [comment]
Fixed in rev 40.
