### ISSUE TITLE
[NPC] Unknown Untargettable NPCs - Should appear dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#578]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the Dawning Wood Catacombs, near Morbent Fel, in Darkshire, there are many ghouls which should appear dead.
![uun0528](https://user-images.githubusercontent.com/82483575/120046035-ec1a8680-bfd6-11eb-93f0-c8783476b268.png)

**How to reproduce:**
Navigate to Morbent Fel in Darkshire. Observe the untargettable Ghouls nearby. They should appear dead.

**How it should work:**
The ghouls should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=43761/morbent-fel

**Comment by HerodDev5** [comment]
Fixed in rev 39.
