### ISSUE TITLE
[QUEST] Lunk's Adventure: Spider Rider - Spider Venom not collectable from Lunk

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#587]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, during the quest Lunk's Adventure: Spider Rider, the Glassweb Venom needed for the quest A Proper Antivenom cannot be collected from Lunk. This makes completing both quests at the same time difficult. Additionally, Lunk will not ride any spiders which are not attacking the player, meaning that Pet classes, such as Warlock and Hunter will have difficulty with the quest.

**How to reproduce:**
With both quests Lunk's Adventure: Spider Rider and A Proper Antivenom, weaken a Glassweb Spider. Observe as Lunk makes the spider disappear and then a green ooze appears on his model. This ooze cannot be interacted with.

**How it should work:**
Once Lunk has ridden the spider, Lunk should be interactable, which should give the player 2 Glassweb Venom.

**Database links:**
https://www.wowhead.com/quest=27959/lunks-adventure-spider-rider
https://www.wowhead.com/quest=27958/a-proper-antivenom

**Comment by HerodDev1** [comment]
Fixed in rev 19.
