### ISSUE TITLE
[NPC] Brother Anton - Should appear to be dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#597]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Brother Anton currently appears to be alive.
![image](https://user-images.githubusercontent.com/82483575/120417947-514ae080-c325-11eb-8af2-d38762c7c7fe.png)

**How to reproduce:**
Navigate to roughly 62.0 91.2 in Desolace. Observe that Brother Anton appears to be alive.

**How it should work:**
Brother Anton should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=1182/brother-anton

**Comment by HerodDev5** [comment]
Fixed in rev 40.
