### ISSUE TITLE
[Profession] Profession Trainer in Goldhain doesnt interact with u 

### ISSUE THREAD

**Issue by Jaydoc1234** [SallyWhitemane/Herod#6]
**Description:**
When talking to Lien Farner, the Profession Trainer in Goldhain, u can select between gathering and crafting profession but nothing else will happen after u selected one of the two options.

**How to reproduce:**
Talk to the dude and select one of the 2 options.

**How it should work:**
He should open another menu with all professions that u can learn.

**Comment by HerodDev** [comment]
fixed rev 7
