### ISSUE TITLE
Miner Fortune quest 

### ISSUE THREAD

**Issue by Proctium11** [SallyWhitemane/Herod#60]
Description:
You cant turn in the quest

How to reproduce:
Get the quest
Go with the boat at Nozzlepot Outpost
Kill mobs at the mine for Cats Eye Emerald
Go turn in the quest but quest doesnt show up neither u can complete it

How it should work:
You should see the question mark and turn in the quest

**Comment by Pallaladin** [comment]
+1 not working can't turn it in

**Comment by HerodDev** [comment]
fixed rev 10
