### ISSUE TITLE
[MAJOR] [INSTANCE] The Nexus - Spawn Location not at correct coordinates.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#602]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The entry location for The Nexus is not located at the correct x,y,z coordinates. When appearing in the instance, all players fall through the map and die.

**How to reproduce:**
Load into The Nexus. Observe that you fall immediately and die.

**How it should work:**
The map should load and the players should not fall through it.

**Database links:**
https://www.wowhead.com/the-nexus

**Comment by cloud1121** [comment]
reference #603

**Comment by HerodDev5** [comment]
Fixed in rev 35
