### ISSUE TITLE
[Quest] Marsh Frog Legs

### ISSUE THREAD

**Issue by pumpkinss** [SallyWhitemane/Herod#606]
**Description:** The Giant Marsh Frogs do not drop the Marsh Frog Legs that are required to complete the quest.

**How to reproduce:** Pick up the quest from "Swamp Eye" Jarl, kill the Giant Marsh Frogs.

**How it should work:** The Giant Marsh Frogs should drop Marsh Frog Legs.

**Database links:** 
https://www.wowhead.com/quest=27183/marsh-frog-legs
https://www.wowhead.com/npc=23979/giant-marsh-frog

**Comment by HerodDev1** [comment]
It drops, 100% in DB

![image](https://user-images.githubusercontent.com/86661453/124463209-d5fca480-dd92-11eb-89cd-4685d281ef61.png)
