### ISSUE TITLE
[Quest] Mudrock Soup and Bugs

### ISSUE THREAD

**Issue by pumpkinss** [SallyWhitemane/Herod#607]
**Description:** The Forked Mudrock Togues don't drop from the Mudrock Spikeshells to complete the quest.

**How to reproduce:** Pick up the quest Mudrock Soup and Bugs, Kill the Mudrock Spikeshells, they will not drop the quest item.

**How it should work:** The Mudrock Spikeshells should drop the Mudrock Tongues to complete the quest.

**Database links:**
https://www.wowhead.com/quest=1204/mudrock-soup-and-bugs
https://www.wowhead.com/item=5883/forked-mudrock-tongue
https://www.wowhead.com/npc=4397/mudrock-spikeshell

**Comment by HerodDev1** [comment]
It drops, 75% in DB.

![image](https://user-images.githubusercontent.com/86661453/124463056-9e8df800-dd92-11eb-9422-e64542221dd9.png)
