### ISSUE TITLE
[Quest] Defias in Dustwallow?

### ISSUE THREAD

**Issue by pumpkinss** [SallyWhitemane/Herod#608]
**Description:** Garn Mathers does not drop the quest item Defias Orders.

**How to reproduce:** Pick up the quest, kill Garn Mathers, the quest item will not drop.

**How it should work:** Defias Orders should drop from Garn Mathers when you pick up the quest.

**Database links:**
https://www.wowhead.com/item=33037/defias-orders
https://www.wowhead.com/npc=23679/garn-mathers
https://www.wowhead.com/quest=27234/defias-in-dustwallow

**Comment by HerodDev1** [comment]
It drops, % in DB is 100%
![image](https://user-images.githubusercontent.com/86661453/124462715-42c36f00-dd92-11eb-97e2-708b29a8a84d.png)
