### ISSUE TITLE
[Quest] The Reagent Thief

### ISSUE THREAD

**Issue by pumpkinss** [SallyWhitemane/Herod#609]
**Description:** The quest item Marsh Venom does not drop from the quest mobs.

**How to reproduce:** Pick up the quest The Reagent Thief, kill the quest mobs, they will not drop Marsh Venom required to complete the quest.

**How it should work:** The quest mobs should drop Marsh Venom to complete the quest.

**Database links:**
https://www.wowhead.com/item=33103/marsh-venom
https://www.wowhead.com/npc=4412/darkfang-creeper
https://www.wowhead.com/npc=4348/noxious-shredder
https://www.wowhead.com/quest=27339/the-reagent-thief

**Comment by HerodDev1** [comment]
Noxious Shredder
![image](https://user-images.githubusercontent.com/86661453/124462243-cd579e80-dd91-11eb-9850-a503cb3fc4fa.png)
Darkfang Creeper
![image](https://user-images.githubusercontent.com/86661453/124462303-dfd1d800-dd91-11eb-85c2-80131f71034a.png)

**Comment by HerodDev1** [comment]
It seems that you were unlucky ;P
