### ISSUE TITLE
Hand-me-downs - mines not exploding (horde quest Aszhara

### ISSUE THREAD

**Issue by SylahUmehara** [SallyWhitemane/Herod#61]
**Description:**
Quest https://www.wowhead.com/quest=14469/hand-me-downs  ,  landmines do not explode while doing quest

**How to reproduce:**
Attempted standing in close proximity, no explosion, stood ontop of them, no explosion

**How it should work:**
Refer to link https://www.wowhead.com/quest=14469/hand-me-downs , their are a couple of videos showing how they work.

Similar to the bombs in Storm-peaks for toolbox quest

**Comment by HerodDev** [comment]
fixed rev 10
