### ISSUE TITLE
[Quest] The Grimtotem Weapon

### ISSUE THREAD

**Issue by pumpkinss** [SallyWhitemane/Herod#610]
**Description:** When killing the Crocolisks with the totem down, the quest objective does not go up.

**How to reproduce:** Pick up the quest The Grimtotem Weapon, place down a totem, kill a Mottled Drywallow Crocolisk, the quest objective will not go up.

**How it should work:** The quest objective should go up whenever you kill a Mottled Drywalloe Crocolisk with the totem down like in this video: https://www.youtube.com/watch?v=v8_3A5Ydx8E

**Database links:**
https://www.wowhead.com/quest=27336/the-grimtotem-weapon
https://www.wowhead.com/item=33101/captured-totem
https://www.wowhead.com/npc=4341/drywallow-crocolisk

**Comment by HerodDev** [comment]
@pumpkinss please just copy&paste wowhead link directly, you dont need to add (url) stuff to it

**Comment by SallyWhitemane** [comment]
Quest is working as intented, remember you have to deliver finishing blow while mobs have aura applied form totem(it stays on them only for 3 sec and is applied every 4 sec to one of nearby mobs).
