### ISSUE TITLE
Diggin' for Worms

### ISSUE THREAD

**Issue by clark1978** [SallyWhitemane/Herod#614]
Stormwind Fishing daily Diggin' for Worms not working. There are no worms at the location to dig up.

How to reproduce: accept daily and ride to pond there are no worm mounds no where in sight.

How it supposed to work: pond is supposed to have worm mounds to dig a worm bait from to catch crystal bass from pond.

https://www.wowhead.com/quest=26420/diggin-for-worms

**Comment by SallyWhitemane** [comment]
Fixed in rev 16.
