### ISSUE TITLE
[QUEST] Destiny Calls - Night Elf Rogue

### ISSUE THREAD

**Issue by Badshot2590** [SallyWhitemane/Herod#621]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The quest "Destiny Calls" for Night Elf Rogue from Syurna cannot be complete.  Sethir the Ancient when killed does not drop the required item "Sethir's Journal" to complete the quest.  I was a level 13 night elf rogue when I received the quest from Syurna in Darnassus.

**How to reproduce:** Receive the quest "Destiny Calls" from Syurna in Darnassus as a Rogue.

**How it should work:**  You should receive the quest item "sethir's Journal" when killing Sethir the Ancient.

**Database links:**
https://classic.wowhead.com/quest=2242/destiny-calls
https://www.wowhead.com/npc=6909/sethir-the-ancient
https://www.wowhead.com/item=7737/sethirs-journal
https://www.wowhead.com/npc=4163/syurna

**Comment by HerodDev1** [comment]
Fixed in rev 19.
