### ISSUE TITLE
[NPC] Slain Cultist - Should appear to be dead.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#631]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Slain Cultist NPCs in The Wailing Ziggurat in Borean Tundra are currently standing as if they are alive. They should appear to be dead.
![image](https://user-images.githubusercontent.com/82483575/122985757-2c65ee00-d364-11eb-82d1-39ff22a360e9.png)

**How to reproduce:**
Head to The Wailing Ziggurat in Borean Tundra. Observe that the Slain Cultists appear to be alive.

**How it should work:**
The Slain Cultists should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=26172/slain-cultist

**Comment by HerodDev5** [comment]
Fixed in rev 38.
