### ISSUE TITLE
[NPC] Steeljaw's Corpse - Should appear to be dead

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#633]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The NPC Steeljaw's Corpse appears to be alive.

![image](https://user-images.githubusercontent.com/82483575/122995083-c2067b00-d36e-11eb-85bd-eff075a3a486.png)

**How to reproduce:**
Navigate to Steelhaw's Caravan in Borean Tundra. Observe that Steeljaw's Corpse appears to be alive.

**How it should work:**
He should appear to be dead.

**Database links:**
https://www.wowhead.com/npc=25384/steeljaws-corpse

**Comment by HerodDev5** [comment]
Fixed in rev 38.
