### ISSUE TITLE
[QUEST] Fueling the Project - Oil Slick uses wrong model

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#635]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Oil Slick objects interacted with during the quest Fueling the Project use the wrong model, using a slime instead of a puddle.

![image](https://user-images.githubusercontent.com/82483575/122998369-8f5e8180-d372-11eb-8dcc-630efd8c1018.png)

**How to reproduce:**
Navigate to the Scalding Pools in Borean Tundra. Observe the untargettable slimes.

**How it should work:**
The slimes should appear as Oil Slicks.

**Database links:**
https://www.wowhead.com/quest=11715/fueling-the-project

**Comment by HerodDev5** [comment]
Fixed in rev 39.
