### ISSUE TITLE
[OBJECT] TEMP Westrift Seismic Activity - Object is visible

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#639]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The TEMP Westrift Seismic Activity object is visible to the player.
![image](https://user-images.githubusercontent.com/82483575/123006230-f97c2400-d37c-11eb-9373-42783090e38a.png)

**How to reproduce:**
Navigate to The Westrift in Borean Tundra. Head to the Seismic Rift below the water. In the rift, observe the small object in the rift, which when moused over shows TEMP Westrift Seismic Activity.

**How it should work:**
This object should be invisible.

**Database links:**

**Comment by HerodDev5** [comment]
Fixed in rev 39.
