### ISSUE TITLE
Redhound Projectile Transit - (Bilgewater Rocket-Jockey's) Aszhara horde transportation

### ISSUE THREAD

**Issue by SylahUmehara** [SallyWhitemane/Herod#64]
**Description:**
Choosing a destination and aggroing causes the rocket to stop and leaves you on it, making you unable to attack with the constant error "Cannot do this right now"

**How to reproduce:**
Speak to a Bilgewater Rocket jockey at either Ogrimmar Rocketway exchange, Gallywix Rocketway exchange, Northern Rocketway Exchange/Terminus

**How it should work:**
Rockets are immune to aggro radius and shouldn't allow the player to gain aggro from moving too close to an NPC 
https://www.wowhead.com/npc=43217/bilgewater-rocket-jockey

**Comment by HerodDev** [comment]
fixed
