### ISSUE TITLE
[Quest] Lost in the Darkness

### ISSUE THREAD

**Issue by HoneyBelly** [SallyWhitemane/Herod#65]
**Description:**
The cocoons for the Quest "Lost in the  Darkness" Eveade everytime. I testet a bunch of them and all of them evade.
Location: Silverpine Forrest -> The Skittering Dark

**How to reproduce:**
Cast, wand, melee attack the cocoons.

**How it should work:**
The cocoons should not evade attacks.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=27093/lost-in-the-darkness

**Comment by HerodDev** [comment]
fixed in rev 14
