### ISSUE TITLE
[NPC] Xink's Shredder - Mount point at incorrect location.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When the player enters Xink's Shredder, the player currently sits on the ground below the shredder.
![image](https://user-images.githubusercontent.com/82483575/123151743-6816bb80-d429-11eb-9b1e-10f518e7ad56.png)

**How to reproduce:**
Enter Xink's Shredder during one of the associated quests, including Lumber Hack.

**How it should work:**
The player should not be visible.

**Database links:**
https://www.wowhead.com/npc=27061/xinks-shredder
https://www.wowhead.com/quest=12050/lumber-hack

**Comment by HerodDev1** [comment]
Fixed in rev 18.
