### ISSUE TITLE
[QUEST] Spiritual Insight - Credit not awarded until long after flight ends

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest, the player uses the provided Toalu'u's Spiritual Incense to take a short flight around Dragonblight. Quest credit is currently awarded only after the buff ends, which is currently 55 seconds after the flight ends.

**How to reproduce:**
Accept the quest. Use the quest item next to the Toalu'u's Brazier object. Observe the flight. Observe that quest credit is not awarded until long after the flight ends.

**How it should work:**
The buff should end upon landing, and quest credit should be awarded at that time.

**Database links:**
https://www.wowhead.com/quest=12028/spiritual-insight

**Comment by HerodDev1** [comment]
Fixed in rev 18.
