### ISSUE TITLE
[QUEST] Never Trust A Big Barb And A Smile

### ISSUE THREAD

**Issue by CeoOfCoronavirus** [SallyWhitemane/Herod#663]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Durotar, Sen'jin Village Quest: When you kill a scorpion and move on to attack another one, the totem you placed down to capture the venom, follows you.

**How to reproduce:**
Do the quest. 

**How it should work:**
The totem should be immobile.

**Database links:**
https://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile

**Comment by HerodDev1** [comment]
Fixed in rev 19.
