### ISSUE TITLE
[OBJECT] Wanted! - Sign in Light's Breach takes 10 seconds to read.

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#668]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Wanted! sign in Light's Breach takes 10 seconds to "open".

https://user-images.githubusercontent.com/82483575/123556287-f2279280-d74f-11eb-96ba-81aa84a1d786.mp4

**How to reproduce:**
Navigate to Light's Breach. Attempt to read the Wanted! sign. Observe that you spend 10 seconds "Opening".

**How it should work:**
The object should be read instantly, immediately offering the quest.

**Database links:**
https://www.wowhead.com/object=191728/wanted

**Comment by HerodDev1** [comment]
Fixed in rev 18.
