### ISSUE TITLE
[QUEST] Making Something Out Of Nothing - Scourge Scrap Metal take 10 seconds to gather

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#669]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Making Something Out Of Nothing, the player must gather 10 Scourge Scrap Metal items. Currently, each node requires 10 seconds to loot.

**How to reproduce:**
Accept the quest Making Something Out Of Nothing. Find a nearby Scourge Scrap Metal node. Attempt to gather. Observe the 10 second timer.

**How it should work:**
Per videos on wowhead, there should be no cast time to gather these items.

**Database links:**
https://www.wowhead.com/quest=12901/making-something-out-of-nothing

**Comment by HerodDev1** [comment]
It has been changed to "point&click"in patch 6.0.2. I can lower that to 2sec.

**Comment by HerodDev1** [comment]
Fixed in rev 19.
