### ISSUE TITLE
Any NPC that requires a dialogue  to be clicked first is broken

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#67]
**Description:** Any NPC that has a dialogue option like this https://i.imgur.com/Qyhrzwk.png, is broken.
 

**How to reproduce:** Click on the dialogue

**How it should work:**  After clicking the option a inventory or any other interface should open

**Comment by HerodDev** [comment]
Please next time write specific issue for specific npc, there are hundreds of npc with gossip option, cant fix all at once.
