### ISSUE TITLE
[QUEST] Gluttonous Lurkers - Basilisks only require 1 rat

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Gluttonous Lurkers, the player must use Zul'Drak Rats gathered from the nearby area on Lurking Basilisks. The quest would normally require 5 rats on each basilisk, however currently only 1 rat is required.

**How to reproduce:**
Accept the quest Gluttonous Lurkers. Grab 1 Zul'Drak Rat. Use the rat on a nearby Lurking Basilisk. Observe that you can immediately harvest the basilisk.

**How it should work:**
Each basilisk should require 5 rats.

**Database links:**
https://www.wowhead.com/quest=12527/gluttonous-lurkers

**Comment by HerodDev1** [comment]
Fixed in rev 18.
