### ISSUE TITLE
[QUEST] I Sense a Disturbance - Event does not start

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#674]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When accepting the quest I Sense a Disturbance, after choosing the dialog option offered by Har'koa, the player should be transported on a vehicle over to the objective, and then back to Har'koa. Currently this is not happening.

**How to reproduce:**
Accept the quest I Sense a Disturbance. Choose the dialog option from Har'koa. Observe that nothing happens.

**How it should work:**
Choosing the dialog option should place the character on a cat vehicle and an event should begin.

**Database links:**
https://www.wowhead.com/quest=12665/i-sense-a-disturbance

**Comment by SallyWhitemane** [comment]
Fixed in rev 21.
