### ISSUE TITLE
[QUEST] Where in the World is Hemet Nesingwary? - Flight event does not trigger

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#675]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When accepting the quest Where in the World is Hemet Nesingwary?, the player should be placed on a flying machine shortly before teleporting to Sholazar Basin. Currently, this event does not trigger.

**How to reproduce:**
Accept the quest Where in the World is Hemet Nesingwary?. Observe that the player is not placed on a flying machine, and no flight event is started.

**How it should work:**
Upon accepting the quest, the flight event should begin.

**Database links:**
https://www.wowhead.com/quest=12521/where-in-the-world-is-hemet-nesingwary

**Comment by HerodDev1** [comment]
Fixed in rev 22.
