### ISSUE TITLE
[QUEST] Still At It - Grammatical errors

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Still At It, "Tipsy" McManus shouts out orders. Currently, one of these orders is "The still need heat!Light the bazier!". This should instead read as "The still needs heat! Light the brazier!" or something similar.
![image](https://user-images.githubusercontent.com/82483575/124496308-e30f9880-dd7e-11eb-989d-2c2092a46793.png)

**How to reproduce:**
Accept the quest Still At It. Perform the event. If the brazier needs to be lit during the event, you will see this line.

**How it should work:**
The quote should read as "The still needs heat! Light the brazier!" or something similar.

**Database links:**
https://www.wowhead.com/quest=12644/still-at-it

**Comment by SallyWhitemane** [comment]
Fixed in rev 28.
