### ISSUE TITLE
[QUEST] A Mammoth Undertaking - Quest credit improperly awarded

### ISSUE THREAD

**Issue by Ahumaya** [SallyWhitemane/Herod#677]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest A Mammoth Undertaking, the player needs to deliver a Shattertusk Mammoth by using the Mammoth Harness item. Currently, the item does not work and quest credit is awarded by killing a Shattertusk Mammoth.

**How to reproduce:**
Accept the quest A Mammoth Undertaking. Find a Shattertusk Mammoth. Attempt to use the Mammoth Harness. Observe that this fails. Kill the Shattertusk Mammoth. Observe that quest credit is awarded.

**How it should work:**
The Mammoth Harness should turn the Shattertusk Mammoth into a vehicle which you return to the quest giver.

**Database links:**
https://www.wowhead.com/quest=12607/a-mammoth-undertaking

**Comment by SallyWhitemane** [comment]
Fixed in rev 28.
