### ISSUE TITLE
quest npc bug in The Hinterlands

### ISSUE THREAD

**Issue by Kreanor** [SallyWhitemane/Herod#678]
**Description:**
In the quest Ongolongo's revenge, The npc Ongolongo is staying
at a doorway near the pit he is supposed to be in instead of being in the pit.
when attacking Ongolongo, the npc says a voiceline while entering and leaving
combat simultaneously and doesn't move.

**How to reproduce:**
Attack the npc Ongolongo in The Hinterlands at a doorway near the pit he is supposed to be in, located in Jintha' Alor.

**How it should work:**
Ongolongo should be in a pit located near the center of Jintha' Alor in the Hinterlands and should be attackable, Ongolongo
will then run away after being attacked and brought to low health.

**Database links:**
https://www.wowhead.com/quest=26515/ongolongos-revenge

**Comment by HerodDev** [comment]
duplicate https://github.com/SallyWhitemane/Herod/issues/161
