### ISSUE TITLE
Eastern Plaguelands (npc bug)

### ISSUE THREAD

**Issue by Kreanor** [SallyWhitemane/Herod#683]
**Description:**
The Crypt Walker, Crypt Stalker, Crypt Slayer, and Crypt Horror npc's stay still even while being attacked  or entering combat with nearby targets and also don't attack the player when the player attacks these npc's but the npc does target and enters combat with the player.

**How to reproduce:**
Enter Terror Web tunnel in Eastern Plaguelands and attack any of these npc's and observe the npc behavior.

**How it should work:**
The npc's should attack and follow the targets they enter combat with and turn in the direction of their targets in addition to entering combat and targeting their targets.

**Database links:**
https://www.wowhead.com/npc=8556/crypt-walker
https://tbc.wowhead.com/npc=8555/crypt-stalker
https://www.wowhead.com/npc=8557/crypt-horror
https://www.wowhead.com/npc=8558/crypt-slayer
https://www.wowhead.com/eastern-plaguelands

**Comment by HerodDev** [comment]
duplicate https://github.com/SallyWhitemane/Herod/issues/163
