### ISSUE TITLE
(Player bug) dead player alive after relog

### ISSUE THREAD

**Issue by Kreanor** [SallyWhitemane/Herod#696]
**Description:**
If the player dies then leaves the game and returns to the game as the dead character, the character resurrects.

**How to reproduce:**
die in game and release then log off and log back onto the dead character and the character may come back to life.

**How it should work:**
The dead character should still be dead after relogging onto that character.

**Database links:**

**Comment by HerodDev5** [comment]
Fixed in rev 35
