### ISSUE TITLE
Eastern Plaguelands (quest npc bug) The Lone Hunter

### ISSUE THREAD

**Issue by Kreanor** [SallyWhitemane/Herod#701]
**Description:**
The Lone Hunter npc located in Eastern Plaguelands near Darrowshire will continue to lay down while attacking and does not display a dying animation.

**How to reproduce:**
Find and attack The Lone Hunter npc and observe the position of the npc.

**How it should work:**
The npc should stand up and attack while displaying attacking, standing, and dying animations at the right times.

**Database links:**
https://www.wowhead.com/npc=45450/the-lone-hunter

**Comment by HerodDev5** [comment]
Fixed in rev 40.
