### ISSUE TITLE
Eastern Plaguelands (npc bug) Darrowshire spirit

### ISSUE THREAD

**Issue by Kreanor** [SallyWhitemane/Herod#702]
**Description:**
Darrowshire spirits after spawning when killing Giberring ghouls become non-clickable after clicking on them and the text box that appears after clicking them disapears immediately. Gibbering ghouls can be found in Corin's Crossing in Eastern Plaguelands.

**How to reproduce:**
Attack and kill a Gibbering ghoul in Corin's Crossing in Eastern Plaguelands and attempt to talk to the Darrowshire spirit that
spawns.

**How it should work:**
The Darrowshire spirit text box that appears should not dissapear immediately and should still be clickable after trying to talk to
the npc.

**Database links:**
https://www.wowhead.com/npc=11064/darrowshire-spirit#objective-of

**Comment by HerodDev5** [comment]
Fixed in rev 40.
