### ISSUE TITLE
Instance [Culling of Stratholme] : Risen zombies give xp

### ISSUE THREAD

**Issue by ChMonta** [SallyWhitemane/Herod#706]
Description:
The risen zombies are a 300 hp mobs that  constantly respawn in COS .These mobs were giving  2.5 to 3k xp per kill  in the last ptr cycle   .... You can realistically get a full cleared id (in normal or heroic)  and invite your alts to a group  and quickly farm xp from 76 to 85 in an hour or less . A  single clear of the zombies  in the walkway between the book shelf and Malganis yields between 275kxp to 300k per clear ... in less than a minute

How to reproduce:
Killing a Risen zombie in Stratholme on a level appropriate char will yield xp 

How it should work:
The Risen zombies should not give xp  ...

**Comment by HerodDev5** [comment]
Fixed in rev 45.
