### ISSUE TITLE
Charge doesnt start auto attack

### ISSUE THREAD

**Issue by CluckyBoomy** [SallyWhitemane/Herod#71]
**Description:**
When charging to a mob as warrior, the character doesnt start attacking.

**How to reproduce:**
Charge, afk.

**How it should work:**
When using charge, it should automatically start your auto attacks.

**Comment by alexspew** [comment]
No? There's a reason why you have /startattack on every single macro as warrior..

**Comment by HerodDev** [comment]
not a bug
