### ISSUE TITLE
Quest: The Pit of Scales

### ISSUE THREAD

**Issue by Aidaidu** [SallyWhitemane/Herod#742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There's no npc, empty space

**How to reproduce:**

**How it should work:**
There should be npc - Tahet and the Pit Master that will send crocs to kill you
https://www.youtube.com/watch?v=ZJk7UbEbEUY

**Database links:**
https://www.wowhead.com/quest=27738/the-pit-of-scales
![WoWScrnShot_090921_174851](https://user-images.githubusercontent.com/90389326/132719574-5c827098-bef1-4a16-b767-43d976581d09.jpg)

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Herod/issues/750 

Closing this issue.
