### ISSUE TITLE
Nightsaber Rider NPCs in Auberdine

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Herod#76]
**Description:**
Currently when you talk to Nightsaber Rider during [The Final Flame of Bashal'aran]  near Lor'danel bridges you have only an option I'd like to travel to Lor'danel, which does nothing(exact same issue happens when you want to travel to the Tower of Athallaxx, the new dialogue option doesn't appear, basically nobody among these riders work)

**How to reproduce:**
Get quest [The Final Flame of Bashal'Aran], but it should be useable even after this quest since this npc should work similar to azshara's rocket -> talk to Nightsaber Rider npc near southeastern bridge -> look at dialogue option

**How it should work:**
NPCs should offer an option "I'd like to travel to Bashal'aran" and after it secure you a passage on nightsaber to Bashal'aran with pathing similar to this video: https://youtu.be/eLdDb3ZnlWE?t=53

**Comment by Bluecow941** [comment]
Same NPC, Nightsaber Rider but in Bashal'aran although it has correct dialogue option, nothing happens after talking to him when it should give you a passage back to Lor'danel

**Comment by HerodDev** [comment]
fixed in rev 14
