### ISSUE TITLE
livin the life quest in westfall animation bug

### ISSUE THREAD

**Issue by manuelinobdk** [SallyWhitemane/Herod#77]
**Description:** char is bugged (the animation)

**How to reproduce:** do the quest

**How it should work:**
you shouldnt see the char and u should be in the box
![Desktop Screenshot 2021 04 12 - 18 27 53 57](https://user-images.githubusercontent.com/82398722/114428880-092cfe80-9bbd-11eb-9adb-c1c8fe148078.png)

**Comment by HerodDev** [comment]
fixed in rev 14
