### ISSUE TITLE
A Load of Croc | 26929 Missing

### ISSUE THREAD

**Issue by alexspew** [SallyWhitemane/Herod#78]
**Description:**
A Load of Croc | 26929 Missing

**How to reproduce:**
Go to npc Cannary Caskshot (44345) -> she only has 1 quest

**How it should work:**
Should be able to get this quest.

**Comment by HerodDev** [comment]
not a bug, need to finsih https://www.wowhead.com/quest=26860/thelsamar-blood-sausages first
