### ISSUE TITLE
[Quest] [Human starting area] Extinguishing Hope - Doesn't share progress in party

### ISSUE THREAD

**Issue by Lapaco94** [SallyWhitemane/Herod#80]
**Description:**
The quest Extinguishing hope, where you put out fires in the wineyard. Doesn't share progress with other party members.

**How to reproduce:**
Be in a party and put out a fire. Party member won't get credit.

**How it should work:**
Party member should get credit from doused fire.

**Comment by HerodDev** [comment]
fixed in rev 14
