### ISSUE TITLE
[Quest] [Hero's Call: Board] Sharing the Hero's Call: westfall quest auto declines.

### ISSUE THREAD

**Issue by Lapaco94** [SallyWhitemane/Herod#81]
**Description:**
When in a party, the quest Hero's Call: Westfall auto declines when shared.

**How to reproduce:**
Try to share quest. It auto declines

**How it should work:**
Party member should be able to accept or decline the quest.

![image](https://user-images.githubusercontent.com/82404667/114435749-cf5ff600-9bc4-11eb-994b-ff04ce0f7211.png)

**Comment by HerodDev** [comment]
was able to properly share, not bugged, propably your party already finished this quest - if otherwise make new issue with more data.
