### ISSUE TITLE
Quest Timely Arrival

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Herod#86]
**Description:**
Currently quest is not completeable. During quest, npc walks her path but when she gets in aggro range of some mob, she just kneels, stands in place and won't move an inch until you kill mob close to her, that isn't even attacking her, but somehow she moves after the closest mob dies. After she reaches dock, she also kneels and disappears, with quest not done

**How to reproduce:**
Accept quest Timely Arrival from her -> try to do quest -> watch her moves -> check at the end if you did quest

**How it should work:**
NPC should be responsive to mobs aggro range and be vurneable for them, attack them, for sure not KNEEL, also quest should be completed at the end. Her walking path is fine, just completing and kneeling/reacting to environment is screwed up

**Comment by HerodDev** [comment]
fixed in rev 14
