### ISSUE TITLE
Quest Ending the Threat

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Herod#87]
**Description:**
I haven't checked if killing mob completes quest, because he has shield that makes him immune to everything, but in current state quest is not completeable. To complete quest, a script must be enabled from dialogue with  Huntress Sandrya Moonfall. She says that she must wait for leader to spawn up, but that leader is alive. I'll add that randomly she says npc does not have shield, but sadly he has.

**How to reproduce:**
Get quest Ending the Threat -> talk to npc giver to enable event -> start event(not)

**How it should work:**
Talking with NPC should enable event that breaks his shield and makes for player possibility to actually kill him and complete the quest. https://www.youtube.com/watch?v=NHvC1K8Vwzk

**Comment by HerodDev** [comment]
fixed in rev 14
