### ISSUE TITLE
Missing Quest Mountaineer Rharen - 41075

### ISSUE THREAD

**Issue by alexspew** [SallyWhitemane/Herod#88]
**Description:**
Missing Quest -> The Stolen Keg - 25395 -> Mountaineer Rharen - 41075

**How to reproduce:**
Go to Mountaineer Rharen, he should have a quest.

**How it should work:**
Should be able to get The Stolen Keg quest

**Comment by HerodDev** [comment]
you need to finish https://www.wowhead.com/quest=26137/checking-on-the-boys first to get this quest.
