### ISSUE TITLE
Ashes to Ashes Quest

### ISSUE THREAD

**Issue by PendingtonFlex** [SallyWhitemane/Herod#92]
**Description:**
Burn down the tents, simple right? Wrong! The flamethrower does nothing! the tent rig must be broken needs to redone.

**How to reproduce:**
go use the flamethrower on tents.

**How it should work:**
tents should burn.

**Comment by HerodDev** [comment]
dont know which quest u are talking about burning tents, but quest ashes to ashes id doable (mess but doable)
https://www.wowhead.com/quest=27086/ashes-to-ashes

if you find proper quest about burning tents make new issue
