### ISSUE TITLE
Quest "Cleasing the Afflicted" broken.

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#95]
**Description:** Furbolgs shouldnt attack you after cleansing them and becoming friendly

**How to reproduce:** Use item, kill corruption.

**How it should work:**
Furbolgs shouldnt attack you after cleansing them and becoming friendly

**Comment by Xenothang** [comment]
https://www.wowhead.com/quest=13545/cleansing-the-afflicted
https://www.youtube.com/watch?v=xbCmP8M-N4M

**Comment by HerodDev** [comment]
fixed rev 17
