### ISSUE TITLE
Warlock Pet In Gilneas cannot be dismissed for quest

### ISSUE THREAD

**Issue by Jwulfgamingtv** [SallyWhitemane/Herod#96]
**Description:**
Quest "From the Shadows Cannot be completed." Quest item require you to summon a pet, but by default warlock pet was summoned. Cannot dismiss imp to use the item that summons hounds.

**How to reproduce:**
Unsure

**How it should work:**
Pet should automatically be dismissed when using the item

**Comment by SallyWhitemane** [comment]
Partialy fixed in rev 30. Current pet will now properly unsummon but it won't get summoned back after quest as it shouldn't work that way (checked both with vids and retail).
