### ISSUE TITLE
Quest with ID 13626 is broken

### ISSUE THREAD

**Issue by ElectrickFun** [SallyWhitemane/Herod#98]
**Description:** Click the corpse while being invisible from using the cloak doesnt work.

**How to reproduce:** Equip cloack, become invis and click the corpse 

**How it should work:** You should be able to loot the corpse while invisible.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=13626/respect-for-the-fallen

**Comment by HerodDev** [comment]
fixed in rev 15
